import type { ExerciseSeed } from "./types";

export const exercises: ExerciseSeed[] = [
  // ------------------------------------------------- talking-about-ongoing-life
  { lessonSlug: "talking-about-ongoing-life", type: "mcq", skill: "grammar", prompt: { question: "Choose the correct sentence." }, options: ["I am working here since March.", "I have been working here since March.", "I work here since March.", "I am work here since March."], correctAnswer: "I have been working here since March.", explanation: "since + starting point needs present perfect continuous (have been + -ing).", difficulty: 1, tags: ["present-perfect-continuous", "since-for"], orderIndex: 1 },
  { lessonSlug: "talking-about-ongoing-life", type: "fill_blank", skill: "grammar", prompt: { sentence: "She ______ (live) in Berlin for five years." }, correctAnswer: "has been living", explanation: "Duration up to now with an action still running: has/has been + -ing.", difficulty: 2, tags: ["present-perfect-continuous"], orderIndex: 2 },
  { lessonSlug: "talking-about-ongoing-life", type: "speak", skill: "fluency", prompt: { target: "I've been learning English for two years, and lately I've been focusing on speaking.", hint: "Say it naturally in one breath. Use 'I've been' twice." }, explanation: "Practises the contraction and the tense in a real self-introduction.", difficulty: 2, tags: ["present-perfect-continuous", "fluency"], orderIndex: 3 },
  { lessonSlug: "talking-about-ongoing-life", type: "mcq", skill: "grammar", prompt: { question: "Which one is WRONG?" }, options: ["We've been waiting for an hour.", "I've been knowing her since college.", "They've been building the house since May.", "He's been working late this week."], correctAnswer: "I've been knowing her since college.", explanation: "know is a state verb — no continuous form: I've known her since college.", difficulty: 2, tags: ["present-perfect-continuous", "state-vs-action-verbs"], orderIndex: 4 },

  // ------------------------------------------------------------------ since-vs-for
  { lessonSlug: "since-vs-for", type: "mcq", skill: "grammar", prompt: { question: "Pick the correct blank: I've been a member ______ 2019." }, options: ["for", "since", "from", "during"], correctAnswer: "since", explanation: "2019 is a starting point → since. A duration like three years → for.", difficulty: 1, tags: ["since-for"], orderIndex: 1 },
  { lessonSlug: "since-vs-for", type: "fill_blank", skill: "grammar", prompt: { sentence: "We waited ______ two hours before the flight." }, correctAnswer: "for", explanation: "'two hours' is a length of time → for.", difficulty: 1, tags: ["since-for"], orderIndex: 2 },
  { lessonSlug: "since-vs-for", type: "mcq", skill: "grammar", prompt: { question: "Which sentence is correct?" }, options: ["I am working here since 3 years.", "I work here since 3 years.", "I have been working here for 3 years.", "I have worked here for 2019."], correctAnswer: "I have been working here for 3 years.", explanation: "Duration (for 3 years) + ongoing action → present perfect continuous. since takes a point (since 2019).", difficulty: 2, tags: ["since-for", "present-perfect-continuous"], orderIndex: 3 },

  // ------------------------------------------------------ articles-that-sound-right
  { lessonSlug: "articles-that-sound-right", type: "mcq", skill: "grammar", prompt: { question: "Choose the correct article." }, options: ["a honest answer", "an honest answer", "the honest is fine", "no article needed"], correctAnswer: "an honest answer", explanation: "'honest' starts with a vowel SOUND, so it takes 'an' — sound, not spelling.", difficulty: 1, tags: ["article-a-an"], orderIndex: 1 },
  { lessonSlug: "articles-that-sound-right", type: "mcq", skill: "grammar", prompt: { question: "Which sentence sounds natural?" }, options: ["I went to market yesterday.", "I went to the market yesterday.", "I went to a market the yesterday.", "I went in market yesterday."], correctAnswer: "I went to the market yesterday.", explanation: "A specific, known place takes 'the'; 'yesterday' takes no article.", difficulty: 1, tags: ["article-the-missing", "article-unneeded"], orderIndex: 2 },
  { lessonSlug: "articles-that-sound-right", type: "fill_blank", skill: "grammar", prompt: { sentence: "Let's grab ___ dinner after the meeting." }, correctAnswer: "", explanation: "Meals in have/get/eat phrases take NO article: grab dinner, after lunch.", difficulty: 2, tags: ["article-meal"], orderIndex: 3 },

  // ----------------------------------------------------- past-tense-while-speaking
  { lessonSlug: "past-tense-while-speaking", type: "mcq", skill: "grammar", prompt: { question: "Choose the correct sentence." }, options: ["I didn't went home early.", "I didn't go home early.", "I didn't had lunch.", "Did you ate already?"], correctAnswer: "I didn't go home early.", explanation: "After didn't/did, the verb stays in its base form.", difficulty: 1, tags: ["did-past"], orderIndex: 1 },
  { lessonSlug: "past-tense-while-speaking", type: "fill_blank", skill: "grammar", prompt: { sentence: "Yesterday I ___ (buy) a new charger and ___ (give) it to my brother." }, correctAnswer: ["bought", "gave"], explanation: "One past time frame → all verbs stay past; both are irregular.", difficulty: 2, tags: ["irregular-past", "tense-shift"], orderIndex: 2 },
  { lessonSlug: "past-tense-while-speaking", type: "speak", skill: "fluency", prompt: { target: "Yesterday I went to the market, bought some fruit, and ran into an old friend.", hint: "Tell it as one past-tense story — no leaks into the present." }, explanation: "Trains sustained past tense under speaking pressure.", difficulty: 2, tags: ["tense-shift", "fluency"], orderIndex: 3 },

  // -------------------------------------------------------------- time-prepositions
  { lessonSlug: "time-prepositions", type: "mcq", skill: "grammar", prompt: { question: "Pick the right preposition: The meeting starts ___ 3 PM ___ Friday." }, options: ["in / on", "at / on", "on / at", "at / in"], correctAnswer: "at / on", explanation: "Clock time → at; days → on. The funnel: at time, on day, in month.", difficulty: 1, tags: ["preposition-time"], orderIndex: 1 },
  { lessonSlug: "time-prepositions", type: "mcq", skill: "grammar", prompt: { question: "Which sentence is correct?" }, options: ["We met in January 2024.", "We met on January 2024.", "We met at January.", "We met in the 2024 January."], correctAnswer: "We met in January 2024.", explanation: "Months and years take 'in'; no article before years.", difficulty: 1, tags: ["preposition-time", "article-unneeded"], orderIndex: 2 },
  { lessonSlug: "time-prepositions", type: "fill_blank", skill: "grammar", prompt: { sentence: "I always wake up ___ 6:30 ___ the morning." }, correctAnswer: ["at", "in"], explanation: "Exact time → at; parts of the day (in the morning) → in.", difficulty: 2, tags: ["preposition-time", "preposition-place"], orderIndex: 3 },

  // ------------------------------------------------------- negatives-that-sound-right
  { lessonSlug: "negatives-that-sound-right", type: "mcq", skill: "grammar", prompt: { question: "Choose the correct negative." }, options: ["I don't know nothing.", "I don't know anything.", "I not know anything.", "I doesn't know anything."], correctAnswer: "I don't know anything.", explanation: "One negative per sentence: don't + anything (or know nothing alone).", difficulty: 1, tags: ["double-negative"], orderIndex: 1 },
  { lessonSlug: "negatives-that-sound-right", type: "fill_blank", skill: "grammar", prompt: { sentence: "He didn't ___ (tell) anybody about the change." }, correctAnswer: "tell", explanation: "Base verb after didn't.", difficulty: 1, tags: ["did-past", "double-negative"], orderIndex: 2 },
  { lessonSlug: "negatives-that-sound-right", type: "mcq", skill: "grammar", prompt: { question: "Which one means the same as 'I know nothing'?" }, options: ["I don't know nothing.", "I don't know anything.", "I not know nothing.", "I doesn't know nothing."], correctAnswer: "I don't know anything.", explanation: "Standard English pairs one not with any-words, never two negatives.", difficulty: 2, tags: ["double-negative"], orderIndex: 3 },

  // ------------------------------------------------------- countable-vs-uncountable
  { lessonSlug: "countable-vs-uncountable", type: "mcq", skill: "grammar", prompt: { question: "Choose the correct sentence." }, options: ["I have many informations.", "I have a lot of information.", "I have an information.", "I have two informations."], correctAnswer: "I have a lot of information.", explanation: "information is uncountable: no -s, no a/an, no many.", difficulty: 1, tags: ["countable-uncountable"], orderIndex: 1 },
  { lessonSlug: "countable-vs-uncountable", type: "fill_blank", skill: "grammar", prompt: { sentence: "Could you give me some ___ (advise) about the interview?" }, correctAnswer: "advice", explanation: "advice is uncountable — no -s and no 'an'.", difficulty: 1, tags: ["countable-uncountable"], orderIndex: 2 },
  { lessonSlug: "countable-vs-uncountable", type: "mcq", skill: "grammar", prompt: { question: "Which is correct?" }, options: ["The furniture here are new.", "The furniture here is new.", "The furnitures are new.", "A furniture is new."], correctAnswer: "The furniture here is new.", explanation: "furniture is uncountable → singular verb, no plural.", difficulty: 2, tags: ["countable-uncountable", "plural-agreement"], orderIndex: 3 },

  // ------------------------------------------------------- questions-that-sound-right
  { lessonSlug: "questions-that-sound-right", type: "mcq", skill: "grammar", prompt: { question: "Fix this question: 'You are agree with me?'" }, options: ["Do you agree with me?", "Are you agree with me?", "You do agree with me?", "Agree you with me?"], correctAnswer: "Do you agree with me?", explanation: "agree is a main verb → needs the helper do; 'be agree' doesn't exist.", difficulty: 1, tags: ["question-form"], orderIndex: 1 },
  { lessonSlug: "questions-that-sound-right", type: "mcq", skill: "grammar", prompt: { question: "Choose the natural version of 'I have one doubt.'" }, options: ["I have a doubt.", "I have one question.", "I contain a doubt.", "I am doubt."], correctAnswer: "I have one question.", explanation: "'Doubt' means uncertainty; questions are questions.", difficulty: 1, tags: ["question-doubt"], orderIndex: 2 },
  { lessonSlug: "questions-that-sound-right", type: "speak", skill: "fluency", prompt: { target: "How do you say this in English? And could you spell it for me?", hint: "Ask both questions with proper do-inversion." }, explanation: "Question inversion is the highest-frequency fix in meetings and classrooms.", difficulty: 2, tags: ["question-form", "fluency"], orderIndex: 3 },

  // ---------------------------------------------------- comparisons-in-conversation
  { lessonSlug: "comparisons-in-conversation", type: "mcq", skill: "grammar", prompt: { question: "Which is correct?" }, options: ["This is more better.", "This is better than that.", "This is most better.", "This is more good."], correctAnswer: "This is better than that.", explanation: "good → better → best; never 'more better'.", difficulty: 1, tags: ["comparative-superlative"], orderIndex: 1 },
  { lessonSlug: "comparisons-in-conversation", type: "fill_blank", skill: "grammar", prompt: { sentence: "It was the ___ (easy) task of the three." }, correctAnswer: "easiest", explanation: "Short adjectives take -est with 'the'.", difficulty: 1, tags: ["comparative-superlative"], orderIndex: 2 },
  { lessonSlug: "comparisons-in-conversation", type: "mcq", skill: "grammar", prompt: { question: "Choose the correct superlative." }, options: ["the most easiest", "the easiest", "the easyest", "most easy"], correctAnswer: "the easiest", explanation: "One marking only: -est OR most, never both.", difficulty: 2, tags: ["comparative-superlative"], orderIndex: 3 },

  // --------------------------------------------------------- conditionals-in-real-life
  { lessonSlug: "conditionals-in-real-life", type: "mcq", skill: "grammar", prompt: { question: "Complete: If it ___ tomorrow, we'll move the picnic indoors." }, options: ["will rain", "rains", "would rain", "rained"], correctAnswer: "rains", explanation: "First conditional: if + present simple, will + base verb.", difficulty: 1, tags: ["conditional-would"], orderIndex: 1 },
  { lessonSlug: "conditionals-in-real-life", type: "mcq", skill: "grammar", prompt: { question: "Which sentence is correct?" }, options: ["If I would have time, I would travel more.", "If I had time, I would travel more.", "If I have time, I would travel more.", "If I had time, I will travel more."], correctAnswer: "If I had time, I would travel more.", explanation: "Second conditional: if + past, would + base. No 'would' in the if-clause.", difficulty: 2, tags: ["conditional-would"], orderIndex: 2 },
  { lessonSlug: "conditionals-in-real-life", type: "write", skill: "writing", prompt: { topic: "Write two sentences: one real plan (first conditional) and one dream (second conditional).", minWords: 30 }, explanation: "Production practice: both conditional families in one answer.", difficulty: 2, tags: ["conditional-would", "writing"], orderIndex: 3 },

  // -------------------------------------------------------------------- word-order-fast
  { lessonSlug: "word-order-fast", type: "mcq", skill: "grammar", prompt: { question: "Which noun phrase is correct?" }, options: ["a red big car", "a big red car", "a car red big", "big a red car"], correctAnswer: "a big red car", explanation: "Order: opinion → size → age → shape → colour. Size comes before colour.", difficulty: 1, tags: ["adjective-order"], orderIndex: 1 },
  { lessonSlug: "word-order-fast", type: "fill_blank", skill: "grammar", prompt: { sentence: "I ___ (always / forget) to mute my mic." }, correctAnswer: "always forget", explanation: "Adverbs of frequency go BEFORE the main verb (but after 'be').", difficulty: 2, tags: ["adjective-order"], orderIndex: 2 },
  { lessonSlug: "word-order-fast", type: "mcq", skill: "grammar", prompt: { question: "Choose the natural sentence." }, options: ["I speak only English fluently.", "I only speak English fluently.", "I speak English only I fluently.", "Only I speak fluently English."], correctAnswer: "I speak English fluently — but if the meaning is 'just one language': I only speak English.", explanation: "'Only' sits right before the word it limits; ambiguous placements confuse listeners.", difficulty: 2, tags: ["adjective-order"], orderIndex: 3 },

  // ------------------------------------------------------------ modals-with-confidence
  { lessonSlug: "modals-with-confidence", type: "mcq", skill: "grammar", prompt: { question: "Choose the correct sentence." }, options: ["I can to drive you.", "I can drive you.", "I cans drive you.", "I can driving you."], correctAnswer: "I can drive you.", explanation: "Modal + bare verb: no 'to', no -s.", difficulty: 1, tags: ["modal-gerund"], orderIndex: 1 },
  { lessonSlug: "modals-with-confidence", type: "fill_blank", skill: "grammar", prompt: { sentence: "You must ___ (check) the numbers before sending." }, correctAnswer: "check", explanation: "must + base verb.", difficulty: 1, tags: ["modal-gerund"], orderIndex: 2 },
  { lessonSlug: "modals-with-confidence", type: "mcq", skill: "grammar", prompt: { question: "Most polite request?" }, options: ["Give me the file.", "You should give me the file.", "Could you share the file when you get a chance?", "Must share file."], correctAnswer: "Could you share the file when you get a chance?", explanation: "Could + softener = polite. Imperatives and must sound demanding at work.", difficulty: 2, tags: ["modal-gerund"], orderIndex: 3 },

  // ----------------------------------------------------------- verb-patterns-that-matter
  { lessonSlug: "verb-patterns-that-matter", type: "mcq", skill: "grammar", prompt: { question: "Choose the correct sentence." }, options: ["I enjoy to read.", "I enjoy reading.", "I enjoy read.", "I enjoying reading."], correctAnswer: "I enjoy reading.", explanation: "enjoy takes the -ing form.", difficulty: 1, tags: ["gerund-vs-infinitive"], orderIndex: 1 },
  { lessonSlug: "verb-patterns-that-matter", type: "mcq", skill: "grammar", prompt: { question: "Fix: 'We discussed about the roadmap. Explain me your plan.'" }, options: ["We discussed the roadmap. Explain your plan to me.", "We discussed about the roadmap. Explain me your plan.", "We talked about roadmap. Explain me.", "We discuss the roadmap to me."], correctAnswer: "We discussed the roadmap. Explain your plan to me.", explanation: "discuss takes a direct object; explain takes thing + to + person.", difficulty: 2, tags: ["discuss-about"], orderIndex: 2 },
  { lessonSlug: "verb-patterns-that-matter", type: "fill_blank", skill: "grammar", prompt: { sentence: "I want ___ (go) home, but I need ___ (finish) this first." }, correctAnswer: ["to go", "to finish"], explanation: "want + to; need + to (the TO family).", difficulty: 1, tags: ["gerund-vs-infinitive"], orderIndex: 3 },

  // ------------------------------------------------------------ state-vs-action-verbs
  { lessonSlug: "state-vs-action-verbs", type: "mcq", skill: "grammar", prompt: { question: "Which sentence is correct?" }, options: ["I am knowing the answer.", "I know the answer.", "I am know the answer.", "I knowing the answer."], correctAnswer: "I know the answer.", explanation: "know is a state verb — simple tenses only.", difficulty: 1, tags: ["stative-verb"], orderIndex: 1 },
  { lessonSlug: "state-vs-action-verbs", type: "mcq", skill: "grammar", prompt: { question: "Choose the correct version." }, options: ["She is wanting an update.", "She wants an update.", "She want an update.", "She wanting update."], correctAnswer: "She wants an update.", explanation: "want is stative → she wants (with -s).", difficulty: 1, tags: ["stative-verb", "subject-verb-agreement"], orderIndex: 2 },
  { lessonSlug: "state-vs-action-verbs", type: "speak", skill: "fluency", prompt: { target: "I see your point, and I believe the deadline is realistic.", hint: "Use two state verbs (see, believe) in the simple tense." }, explanation: "Builds the habit of keeping state verbs simple.", difficulty: 2, tags: ["stative-verb"], orderIndex: 3 },

  // -------------------------------------------------------------- feelings-ed-vs-ing
  { lessonSlug: "feelings-ed-vs-ing", type: "mcq", skill: "grammar", prompt: { question: "Complete: The documentary was ___ — I felt ___ halfway through." }, options: ["boring / bored", "bored / boring", "bored / bored", "boring / boring"], correctAnswer: "boring / bored", explanation: "The cause is -ing; the person's feeling is -ed.", difficulty: 1, tags: ["ed-ing-adjective"], orderIndex: 1 },
  { lessonSlug: "feelings-ed-vs-ing", type: "fill_blank", skill: "grammar", prompt: { sentence: "I'm ___ (interest) in AI, and the lecture was ___ (interest)." }, correctAnswer: ["interested", "interesting"], explanation: "-ed = your feeling, -ing = what causes it.", difficulty: 1, tags: ["ed-ing-adjective"], orderIndex: 2 },
  { lessonSlug: "feelings-ed-vs-ing", type: "mcq", skill: "grammar", prompt: { question: "Which is correct?" }, options: ["I was exciting by the news.", "I was excited by the news.", "The news was excited.", "I am exciting about it."], correctAnswer: "I was excited by the news.", explanation: "People feel -ed; things are -ing.", difficulty: 2, tags: ["ed-ing-adjective"], orderIndex: 3 },

  // ----------------------------------------------------------- connectors-for-smooth-speech
  { lessonSlug: "connectors-for-smooth-speech", type: "mcq", skill: "grammar", prompt: { question: "Choose the correct sentence." }, options: ["Although it was late, but we continued.", "Although it was late, we continued.", "It was late, although but we continued.", "But although it was late, but."], correctAnswer: "Although it was late, we continued.", explanation: "although already means 'but' — never stack them.", difficulty: 1, tags: ["although-but"], orderIndex: 1 },
  { lessonSlug: "connectors-for-smooth-speech", type: "fill_blank", skill: "grammar", prompt: { sentence: "The deadline moved, ___ we adjusted the plan." }, correctAnswer: "so", explanation: "Result connector: cause, so result. (Not 'because...so'.)", difficulty: 2, tags: ["although-but"], orderIndex: 2 },
  { lessonSlug: "connectors-for-smooth-speech", type: "write", skill: "writing", prompt: { topic: "Write 3 sentences about a challenge using however, as a result, and even though.", minWords: 40 }, explanation: "Connector variety is what makes writing (and speaking) sound organized.", difficulty: 2, tags: ["although-but", "writing"], orderIndex: 3 },

  // ---------------------------------------------------------------------------- make-vs-do
  { lessonSlug: "make-vs-do", type: "mcq", skill: "vocabulary", prompt: { question: "Choose the correct collocation." }, options: ["do a mistake", "make a mistake", "make the homework", "do a progress"], correctAnswer: "make a mistake", explanation: "make = create (mistake, progress, decision); do = perform (homework, business).", difficulty: 1, tags: ["made-mistake"], orderIndex: 1 },
  { lessonSlug: "make-vs-do", type: "fill_blank", skill: "vocabulary", prompt: { sentence: "Before we ship, ___ sure the tests pass." }, correctAnswer: "make", explanation: "Fixed phrase: make sure.", difficulty: 1, tags: ["made-mistake"], orderIndex: 2 },
  { lessonSlug: "make-vs-do", type: "mcq", skill: "vocabulary", prompt: { question: "Which is correct?" }, options: ["I made my homework.", "I did my homework.", "I did a decision.", "I made my best."], correctAnswer: "I did my homework.", explanation: "Homework takes do; decisions take make.", difficulty: 2, tags: ["made-mistake"], orderIndex: 3 },

  // -------------------------------------------------------------- agreement-in-fast-speech
  { lessonSlug: "agreement-in-fast-speech", type: "mcq", skill: "grammar", prompt: { question: "Choose the correct sentence." }, options: ["He don't like the plan.", "He doesn't like the plan.", "He doesn't likes the plan.", "He not like the plan."], correctAnswer: "He doesn't like the plan.", explanation: "he/she/it + doesn't + base verb.", difficulty: 1, tags: ["subject-verb-agreement"], orderIndex: 1 },
  { lessonSlug: "agreement-in-fast-speech", type: "fill_blank", skill: "grammar", prompt: { sentence: "Everyone ___ (be) welcome, and each of them ___ (have) a badge." }, correctAnswer: ["is", "has"], explanation: "everyone and each take singular verbs.", difficulty: 2, tags: ["plural-agreement"], orderIndex: 2 },
  { lessonSlug: "agreement-in-fast-speech", type: "mcq", skill: "grammar", prompt: { question: "Fix: 'The list of items are ready.'" }, options: ["The list of items are ready.", "The list of items is ready.", "The lists of items is ready.", "The item of list are ready."], correctAnswer: "The list of items is ready.", explanation: "The verb agrees with 'list' (singular), not 'items'.", difficulty: 2, tags: ["plural-agreement"], orderIndex: 3 },

  // --------------------------------------------------------- introduce-yourself-naturally
  { lessonSlug: "introduce-yourself-naturally", type: "mcq", skill: "fluency", prompt: { question: "Which introduction is natural?" }, options: ["Myself Rahul, I am working in TCS.", "I'm Rahul, and I've been at TCS for four years.", "My name is Rahul sir.", "Rahul this side, working TCS."], correctAnswer: "I'm Rahul, and I've been at TCS for four years.", explanation: "'Myself + name' is a translated form; introductions use I'm / My name is.", difficulty: 1, tags: ["myself-intro"], orderIndex: 1 },
  { lessonSlug: "introduce-yourself-naturally", type: "speak", skill: "fluency", prompt: { target: "Hi, I'm Ananya — I've been a product designer for three years, mostly working on fintech apps. How about you?", hint: "Name + what you do + hook + hand back. Under 15 seconds." }, explanation: "The standard casual introduction template.", difficulty: 1, tags: ["myself-intro", "fluency"], orderIndex: 2 },
  { lessonSlug: "introduce-yourself-naturally", type: "mcq", skill: "fluency", prompt: { question: "Someone's name went out of your head. What do you say?" }, options: ["What is your good name?", "Sorry, I didn't catch your name.", "Your name, please tell.", "Who are you?"], correctAnswer: "Sorry, I didn't catch your name.", explanation: "'Good name' isn't used this way in English — 'good name' means reputation.", difficulty: 1, tags: ["good-name"], orderIndex: 3 },

  // -------------------------------------------------------- sound-native-without-fillers
  { lessonSlug: "sound-native-without-fillers", type: "mcq", skill: "fluency", prompt: { question: "Remove the fillers: 'Actually, I basically work, you know, remotely.'" }, options: ["I work remotely.", "Actually I work remotely.", "I, like, work remotely.", "Basically, remotely I work."], correctAnswer: "I work remotely.", explanation: "Filler words add hesitation, not meaning — cut them.", difficulty: 1, tags: ["filler-actually", "filler-basically", "filler-you-know"], orderIndex: 1 },
  { lessonSlug: "sound-native-without-fillers", type: "speak", skill: "fluency", prompt: { target: "The launch went well — we shipped on time, support volume stayed low, and the client signed the renewal.", hint: "Say it in 15 seconds with zero filler words." }, explanation: "Practise clean delivery with a three-part list.", difficulty: 2, tags: ["filler-actually", "fluency"], orderIndex: 2 },
  { lessonSlug: "sound-native-without-fillers", type: "mcq", skill: "fluency", prompt: { question: "Which reply sounds most confident?" }, options: ["Um, so, like, I think it's fine?", "It's fine.", "You know, it's kind of fine, I guess.", "Actually, basically fine."], correctAnswer: "It's fine.", explanation: "Short clean statements read as certainty; stacked fillers read as doubt.", difficulty: 1, tags: ["filler-like", "filler-you-know"], orderIndex: 3 },

  // ------------------------------------------------------------ pauses-that-sound-confident
  { lessonSlug: "pauses-that-sound-confident", type: "mcq", skill: "fluency", prompt: { question: "Where should a pause go?" }, options: ["Between 'the' and its noun", "At clause boundaries", "Before every word", "At the end of every filler"], correctAnswer: "At clause boundaries", explanation: "Pause where the grammar allows it — after opener, between clauses, before numbers.", difficulty: 1, tags: ["long-pauses"], orderIndex: 1 },
  { lessonSlug: "pauses-that-sound-confident", type: "mcq", skill: "fluency", prompt: { question: "Which sounds more confident mid-answer?" }, options: ["Um... uh... I think... maybe...", "(silent beat) I think we should ship Friday.", "Like... I dunno... maybe Friday?", "You know... Friday? I guess?"], correctAnswer: "(silent beat) I think we should ship Friday.", explanation: "Silent pauses signal thinking; filled pauses signal searching.", difficulty: 1, tags: ["filled-pauses"], orderIndex: 2 },
  { lessonSlug: "pauses-that-sound-confident", type: "speak", skill: "fluency", prompt: { target: "The team grew from twelve to forty in a year — which is why our process had to change.", hint: "Pause only after 'year'. No um/uh anywhere." }, explanation: "Numbers force pacing; one well-placed pause structures the sentence.", difficulty: 3, tags: ["long-pauses", "filled-pauses", "fluency"], orderIndex: 3 },

  // ----------------------------------------------------------- expand-your-sentence-range
  { lessonSlug: "expand-your-sentence-range", type: "mcq", skill: "vocabulary", prompt: { question: "Level-up: 'The work is very busy. It is very stressful.' Best rewrite?" }, options: ["The work is very very busy and stressful.", "The work is hectic and stressful.", "The work is busy. The work is stressful.", "Work is busy-stressful."], correctAnswer: "The work is hectic and stressful.", explanation: "Swap repeated intensifiers for precise synonyms.", difficulty: 2, tags: ["word-repetition", "very-much-good"], orderIndex: 1 },
  { lessonSlug: "expand-your-sentence-range", type: "reorder", skill: "grammar", prompt: { instruction: "Build a complex sentence from these parts.", words: ["although", "the deadline moved", "we shipped", "on time"] }, correctAnswer: ["although", "the deadline moved", "we shipped", "on time"], explanation: "Concession clause first, main clause second.", difficulty: 2, tags: ["although-but"], orderIndex: 2 },
  { lessonSlug: "expand-your-sentence-range", type: "speak", skill: "fluency", prompt: { target: "I finished the report, which is why the dashboard is ready — although the data still needs a final check.", hint: "Use 'which' and 'although' in one breath." }, explanation: "Relative + concession clauses upgrade any answer.", difficulty: 3, tags: ["word-repetition", "fluency"], orderIndex: 3 },

  // ------------------------------------------------------ agreeing-and-disagreeing-smoothly
  { lessonSlug: "agreeing-and-disagreeing-smoothly", type: "mcq", skill: "fluency", prompt: { question: "You disagree with a colleague's estimate. Most natural?" }, options: ["No, you are wrong.", "I see your point — from my side the data looked different.", "Yes, no, maybe.", "You don't understand."], correctAnswer: "I see your point — from my side the data looked different.", explanation: "Acknowledge + your view + question keeps the conversation open.", difficulty: 1, tags: ["i-agree-too-much"], orderIndex: 1 },
  { lessonSlug: "agreeing-and-disagreeing-smoothly", type: "mcq", skill: "fluency", prompt: { question: "Vary your agreement: which replaces 'Yes, yes' naturally?" }, options: ["That's right — and I'd add one caveat.", "Yes. Yes.", "Agree agree.", "Correct, correct, correct."], correctAnswer: "That's right — and I'd add one caveat.", explanation: "Agreement plus one addition sounds engaged, not scripted.", difficulty: 1, tags: ["i-agree-too-much"], orderIndex: 2 },
  { lessonSlug: "agreeing-and-disagreeing-smoothly", type: "speak", skill: "fluency", prompt: { target: "I'd say so, mostly — although we should double-check the sample size before committing.", hint: "Partial agreement in one sentence, no 'yes'." }, explanation: "Partial agreement is the backbone of meetings.", difficulty: 2, tags: ["i-agree-too-much", "fluency"], orderIndex: 3 },

  // ------------------------------------------------------------- sounding-confident-intonation
  { lessonSlug: "sounding-confident-intonation", type: "mcq", skill: "pronunciation", prompt: { question: "A statement should end with..." }, options: ["rising pitch (like a question)", "falling pitch", "flat monotone", "a long pause"], correctAnswer: "falling pitch", explanation: "Declaratives fall at the end; rising tails make statements sound uncertain.", difficulty: 1, tags: ["ending-sentences-up"], orderIndex: 1 },
  { lessonSlug: "sounding-confident-intonation", type: "mcq", skill: "pronunciation", prompt: { question: "Which stresses the right word? 'I finished it ___.'" }, options: ["I FINished it today.", "I finished it toDAY.", "I finished it today.", "I finished IT today."], correctAnswer: "I finished it toDAY.", explanation: "Stress the new/key information — here, when it was finished.", difficulty: 2, tags: ["ending-sentences-up"], orderIndex: 2 },
  { lessonSlug: "sounding-confident-intonation", type: "speak", skill: "pronunciation", prompt: { target: "The deadline is Friday. That's the plan. Any questions?", hint: "First two fall at the end; the last one rises." }, explanation: "Statement-fall / question-rise in one mini-drill.", difficulty: 2, tags: ["ending-sentences-up"], orderIndex: 3 },

  // --------------------------------------------------------- intensifiers-without-overdoing
  { lessonSlug: "intensifiers-without-overdoing", type: "mcq", skill: "vocabulary", prompt: { question: "Choose the natural sentence." }, options: ["The food was very much good.", "The food was really good.", "The food was too much good.", "The food was very much delicious."], correctAnswer: "The food was really good.", explanation: "very/really + adjective; very much + verbs only.", difficulty: 1, tags: ["very-much-good"], orderIndex: 1 },
  { lessonSlug: "intensifiers-without-overdoing", type: "fill_blank", skill: "vocabulary", prompt: { sentence: "I like this feature ___ (much)." }, correctAnswer: "very much", explanation: "With verbs: like it very much (not 'very like').", difficulty: 1, tags: ["very-much-good"], orderIndex: 2 },
  { lessonSlug: "intensifiers-without-overdoing", type: "mcq", skill: "vocabulary", prompt: { question: "Replace 'very good' precisely: 'The prototype is ___.'" }, options: ["very much good", "exceptionally good", "too much good", "goodly very"], correctAnswer: "exceptionally good", explanation: "One precise intensifier beats stacked vague ones.", difficulty: 2, tags: ["very-much-good"], orderIndex: 3 },

  // --------------------------------------------------------------- th-sounds-in-everyday-words
  { lessonSlug: "th-sounds-in-everyday-words", type: "mcq", skill: "pronunciation", prompt: { question: "Which is the correct pronunciation of 'think'?" }, options: ["/tɪŋk/ (tink)", "/θɪŋk/ (tongue between teeth)", "/sɪŋk/", "/dɪŋk/"], correctAnswer: "/θɪŋk/ (tongue between teeth)", explanation: "Voiceless /θ/: tongue tip lightly between upper teeth and lower lip, air flows.", difficulty: 1, tags: ["th-sound"], orderIndex: 1 },
  { lessonSlug: "th-sounds-in-everyday-words", type: "speak", skill: "pronunciation", prompt: { target: "I think thirty-three things about this thesis.", hint: "Every 'th' — tongue visibly between the teeth." }, explanation: "Concentrated /θ/ drill mixing think, thirty-three, this, thesis.", difficulty: 2, tags: ["th-sound"], orderIndex: 2 },
  { lessonSlug: "th-sounds-in-everyday-words", type: "mcq", skill: "pronunciation", prompt: { question: "Which transcription is right for 'this'?" }, options: ["/dɪs/", "/ðɪs/", "/tɪs/", "/zɪs/"], correctAnswer: "/ðɪs/", explanation: "'this' uses voiced /ð/ — same mouth position as /θ/ but with voice.", difficulty: 2, tags: ["th-sound"], orderIndex: 3 },

  // ---------------------------------------------------------------------------- w-vs-v-sounds
  { lessonSlug: "w-vs-v-sounds", type: "mcq", skill: "pronunciation", prompt: { question: "How is /v/ produced?" }, options: ["Lips rounded, no teeth contact", "Upper teeth touch lower lip, voiced", "Tongue between teeth, voiceless", "Back of tongue on roof of mouth"], correctAnswer: "Upper teeth touch lower lip, voiced", explanation: "/v/ = teeth-on-lip with voice; /w/ = rounded lips only.", difficulty: 1, tags: ["vw-sound"], orderIndex: 1 },
  { lessonSlug: "w-vs-v-sounds", type: "speak", skill: "pronunciation", prompt: { target: "Victor wasted a very warm winter.", hint: "Alternate /v/ and /w/ deliberately — teeth in, lips out." }, explanation: "Classic minimal-pair alternating drill.", difficulty: 2, tags: ["vw-sound"], orderIndex: 2 },
  { lessonSlug: "w-vs-v-sounds", type: "mcq", skill: "pronunciation", prompt: { question: "Which pair is a true minimal pair for /v/ and /w/?" }, options: ["vine / wine", "cat / bat", "ship / sheep", "light / night"], correctAnswer: "vine / wine", explanation: "vine vs. wine differs only in /v/ vs /w/ — the definition of a minimal pair.", difficulty: 2, tags: ["vw-sound"], orderIndex: 3 },

  // --------------------------------------------------------------------- emails-that-get-replies
  { lessonSlug: "emails-that-get-replies", type: "mcq", skill: "writing", prompt: { question: "Choose the strongest email ask." }, options: ["Kindly do the needful and revert back at the earliest.", "Could you review the attached proposal and send comments by Thursday?", "Please do the needful.", "Update me."], correctAnswer: "Could you review the attached proposal and send comments by Thursday?", explanation: "Specific action + deadline + natural phrasing gets replies.", difficulty: 1, tags: ["do-the-needful", "revert-back", "could-you-kindly"], orderIndex: 1 },
  { lessonSlug: "emails-that-get-replies", type: "mcq", skill: "writing", prompt: { question: "Which opening should you cut?" }, options: ["Hi Priya — quick question about the sprint.", "I hope this email finds you well and in good spirits.", "Attaching the Q3 numbers here.", "Could you confirm by 3 PM?"], correctAnswer: "I hope this email finds you well and in good spirits.", explanation: "Ceremonial openers delay the ask; get to the point kindly.", difficulty: 1, tags: ["could-you-kindly"], orderIndex: 2 },
  { lessonSlug: "emails-that-get-replies", type: "write", skill: "writing", prompt: { topic: "Write a 4-line email asking a colleague for feedback on a design by Friday. No 'kindly', no 'revert'.", minWords: 40 }, explanation: "Context → ask (bold) → deadline → courtesy.", difficulty: 2, tags: ["revert-back", "do-the-needful", "writing"], orderIndex: 3 },

  // -------------------------------------------------------------------- meetings-voice-updates
  { lessonSlug: "meetings-voice-updates", type: "mcq", skill: "fluency", prompt: { question: "Best 20-second update structure?" }, options: ["Status → blocker → ask", "Everything you did today", "Apologies → filler → story", "Ask first, context never"], correctAnswer: "Status → blocker → ask", explanation: "Listeners need where you are, what's stuck, what you need — in that order.", difficulty: 1, tags: ["fluency"], orderIndex: 1 },
  { lessonSlug: "meetings-voice-updates", type: "speak", skill: "fluency", prompt: { target: "Quick update — the importer is done and tested. I'm blocked on staging access; if DevOps grants it today, I'll close by tomorrow noon.", hint: "Three beats, under 25 seconds." }, explanation: "Full status-blocker-ask simulation.", difficulty: 2, tags: ["fluency"], orderIndex: 2 },
  { lessonSlug: "meetings-voice-updates", type: "mcq", skill: "fluency", prompt: { question: "You're interrupted mid-point. What now?" }, options: ["Keep talking louder", "Finish the sentence, then: to finish my point —", "Stay silent forever", "Restart from the beginning"], correctAnswer: "Finish the sentence, then: to finish my point —", explanation: "Claim the floor politely instead of competing for it.", difficulty: 1, tags: ["fluency"], orderIndex: 3 },

  // ------------------------------------------------------------------------ small-talk-that-works
  { lessonSlug: "small-talk-that-works", type: "mcq", skill: "fluency", prompt: { question: "Which opener is safe before a call?" }, options: ["How much do you earn?", "How's your week going so far?", "Who did you vote for?", "Do you have any medical issues?"], correctAnswer: "How's your week going so far?", explanation: "Light, shared-context topics only — politics, salary and health are off-limits.", difficulty: 1, tags: ["fluency"], orderIndex: 1 },
  { lessonSlug: "small-talk-that-works", type: "speak", skill: "fluency", prompt: { target: "Hey! How's your week going? — Busy, we just moved the release up. — Same on our side. Anyway, shall we get into it?", hint: "Play both sides out loud, then swap roles." }, explanation: "Open → share → hand back → exit line, the full small-talk loop.", difficulty: 2, tags: ["fluency"], orderIndex: 2 },
  { lessonSlug: "small-talk-that-works", type: "mcq", skill: "fluency", prompt: { question: "Best exit line to start the meeting?" }, options: ["Anyway, shall we get started?", "OK bye.", "So, yeah...", "I don't know what to say."], correctAnswer: "Anyway, shall we get started?", explanation: "A clean bridge from social to work.", difficulty: 1, tags: ["fluency"], orderIndex: 3 },

  // ----------------------------------------------------------------------- talk-about-your-education
  { lessonSlug: "talk-about-your-education", type: "mcq", skill: "fluency", prompt: { question: "Natural way to say it?" }, options: ["I passed out of Delhi University in 2020.", "I graduated from Delhi University in 2020.", "I was passed out from DU.", "Delhi University passed me in 2020."], correctAnswer: "I graduated from Delhi University in 2020.", explanation: "'pass out' reads as fainting (or regional) — internationally say graduated.", difficulty: 1, tags: ["passed-out"], orderIndex: 1 },
  { lessonSlug: "talk-about-your-education", type: "speak", skill: "fluency", prompt: { target: "I completed my B.Tech in computer science from VNIT in 2021, where I focused on distributed systems.", hint: "Degree → institution → year → focus. Ten seconds." }, explanation: "The three-beat education answer.", difficulty: 1, tags: ["passed-out"], orderIndex: 2 },
  { lessonSlug: "talk-about-your-education", type: "mcq", skill: "fluency", prompt: { question: "Still studying? Choose the natural line." }, options: ["I have not yet passed out.", "I'm in my final year, graduating next May.", "I am doing study still.", "My study is going on."], correctAnswer: "I'm in my final year, graduating next May.", explanation: "Present continuous + future date shows timeline cleanly.", difficulty: 2, tags: ["passed-out"], orderIndex: 3 },

  // ---------------------------------------------------------------------- interview-story-method
  { lessonSlug: "interview-story-method", type: "mcq", skill: "fluency", prompt: { question: "STAR's Action section should mostly use..." }, options: ["'We' for the team's work", "'I' for what YOU did", "Passive voice", "No verbs"], correctAnswer: "'I' for what YOU did", explanation: "Situation/task set context; action is where your contribution is unmistakable.", difficulty: 1, tags: ["fluency"], orderIndex: 1 },
  { lessonSlug: "interview-story-method", type: "reorder", skill: "fluency", prompt: { instruction: "Put the STAR beats in order.", words: ["Result: shipped with zero P1s", "Situation: client moved launch up", "Action: cut scope, daily QA checks", "Task: I owned the release"] }, correctAnswer: ["Situation: client moved launch up", "Task: I owned the release", "Action: cut scope, daily QA checks", "Result: shipped with zero P1s"], explanation: "S → T → A → R, ending on a number.", difficulty: 1, tags: ["fluency"], orderIndex: 2 },
  { lessonSlug: "interview-story-method", type: "write", skill: "writing", prompt: { topic: "Write a 90-second STAR answer to: 'Tell me about a time you handled a tight deadline.' Include one number.", minWords: 80 }, explanation: "Written rehearsal makes spoken delivery automatic.", difficulty: 3, tags: ["fluency", "writing"], orderIndex: 3 },

  // ---------------------------------------------------------------------- collocations-for-impact
  { lessonSlug: "collocations-for-impact", type: "mcq", skill: "vocabulary", prompt: { question: "Choose the correct collocation." }, options: ["make a concern", "raise a concern", "do a concern", "build a concern"], correctAnswer: "raise a concern", explanation: "raise + concern is the fixed pair.", difficulty: 1, tags: ["made-mistake"], orderIndex: 1 },
  { lessonSlug: "collocations-for-impact", type: "mcq", skill: "vocabulary", prompt: { question: "Which is correct?" }, options: ["do a meeting", "hold a meeting", "make a meeting", "build a meeting"], correctAnswer: "hold a meeting", explanation: "hold/conduct/run a meeting — never 'do a meeting'.", difficulty: 1, tags: ["made-mistake"], orderIndex: 2 },
  { lessonSlug: "collocations-for-impact", type: "fill_blank", skill: "vocabulary", prompt: { sentence: "Please ___ (keep) in mind the timezone difference." }, correctAnswer: "keep", explanation: "Fixed phrase: keep in mind.", difficulty: 2, tags: ["made-mistake"], orderIndex: 3 },

  // --------------------------------------------------------------------- precision-words-for-essays
  { lessonSlug: "precision-words-for-essays", type: "mcq", skill: "vocabulary", prompt: { question: "Upgrade: 'very bad for attention' → best option?" }, options: ["very much bad", "detrimental to sustained attention", "too much bad", "super badness"], correctAnswer: "detrimental to sustained attention", explanation: "One precise word replaces vague intensifiers entirely.", difficulty: 2, tags: ["very-much-good"], orderIndex: 1 },
  { lessonSlug: "precision-words-for-essays", type: "mcq", skill: "vocabulary", prompt: { question: "Which hedge is academically safe?" }, options: ["This proves that...", "This suggests that...", "This is 100% the truth.", "Everyone knows that..."], correctAnswer: "This suggests that...", explanation: "Hedges (suggests, tends to, appears to) protect claims you haven't fully proven.", difficulty: 2, tags: ["very-much-good"], orderIndex: 2 },
  { lessonSlug: "precision-words-for-essays", type: "write", skill: "writing", prompt: { topic: "Rewrite this sentence three ways with precision words: 'Social media is very much bad for young people.'", minWords: 40 }, explanation: "Practice producing precision, not just recognizing it.", difficulty: 3, tags: ["very-much-good", "writing"], orderIndex: 3 },
];
