import type { LessonSeed } from "./types";

export const lessons: LessonSeed[] = [
  // ============================================================ english-foundations
  {
    slug: "talking-about-ongoing-life",
    courseSlug: "english-foundations",
    title: "Talking about ongoing life",
    category: "grammar",
    level: "intermediate",
    summary: "Present perfect continuous: the tense for everything that started then and hasn't stopped.",
    durationMin: 8,
    orderIndex: 1,
    skillFocus: "grammar",
    content: {
      blocks: [
        { type: "concept", title: "have/has been + verb-ing", body: "Use it when an action started in the past and continues NOW. It answers “how long?” — I have been learning English for two years. The starting point (since 2024) or the duration (for two years) is usually attached." },
        { type: "example", wrong: "I am working here since 2023.", right: "I have been working here since 2023.", note: "since = starting point, for = length of time" },
        { type: "example", wrong: "She is living in Pune from 2019.", right: "She has been living in Pune since 2019." },
        { type: "example", wrong: "We study English for six months.", right: "We have been studying English for six months." },
        { type: "tips", items: [
          "Present continuous (I am working) = right now only.",
          "Present perfect continuous (I have been working) = from then until now, still true.",
          "This tense is what interviewers mean by “tell me about yourself” — your story so far.",
        ] },
      ],
      keyPhrases: ["I've been working on...", "I've been learning... for...", "That's been going on since...", "Lately I've been focused on..."],
    },
  },
  {
    slug: "since-vs-for",
    courseSlug: "english-foundations",
    title: "Since vs. for",
    category: "grammar",
    level: "beginner",
    summary: "One of the most frequent spoken errors: starting point vs. length of time.",
    durationMin: 6,
    orderIndex: 2,
    skillFocus: "grammar",
    content: {
      blocks: [
        { type: "concept", title: "The two questions", body: "FOR answers “how long?” (for three years, for a week, for ages). SINCE answers “since when?” (since 2020, since Monday, since I graduated). A number plus a time unit is always FOR." },
        { type: "example", wrong: "I know him since college.", right: "I have known him since college." },
        { type: "example", wrong: "We waited since two hours.", right: "We waited for two hours." },
        { type: "tips", items: [
          "Test: replace the phrase with a number — “three years” → FOR.",
          "since 2019 / since last week / since I joined → SINCE.",
          "Pair it with present perfect continuous for talking about your life.",
        ] },
      ],
      keyPhrases: ["for three years", "since I started", "for ages", "since then"],
    },
  },
  {
    slug: "articles-that-sound-right",
    courseSlug: "english-foundations",
    title: "Articles that sound right",
    category: "grammar",
    level: "beginner",
    summary: "a / an / the / nothing — the four choices that make speech feel effortless or foreign.",
    durationMin: 9,
    orderIndex: 3,
    skillFocus: "grammar",
    content: {
      blocks: [
        { type: "concept", title: "The decision tree", body: "First ask: is the listener picturing the SAME thing you are? Yes → the. No, countable, first mention → a/an (based on SOUND: a university, an hour). Not countable or general → nothing: Life is short. Go to work. Have dinner." },
        { type: "example", wrong: "She is a honest person.", right: "She is an honest person.", note: "an before a VOWEL SOUND, not a vowel letter" },
        { type: "example", wrong: "I went to market and then in office.", right: "I went to the market and then to the office." },
        { type: "example", wrong: "Let's order a dinner. We met in the 2021.", right: "Let's order dinner. We met in 2021." },
        { type: "tips", items: [
          "No article: go home, go to work/school, at breakfast (general routines).",
          "the: go to the office/market/airport (specific, shared knowledge).",
          "Years, months, weekdays never take the: in 2026, on Monday.",
        ] },
      ],
      keyPhrases: ["a lot of", "the thing is", "in the morning", "go home", "at work"],
    },
  },
  {
    slug: "past-tense-while-speaking",
    courseSlug: "english-foundations",
    title: "Past tense while speaking",
    category: "grammar",
    level: "intermediate",
    summary: "Tell yesterday's story without dropping into the present halfway through.",
    durationMin: 8,
    orderIndex: 4,
    skillFocus: "grammar",
    content: {
      blocks: [
        { type: "concept", title: "Pick a tense and stay there", body: "When the story's time frame is past, every main verb stays past: went, bought, paid, met, came back. The #1 leak is irregular verbs and “didn't + past” — both take the base form after did." },
        { type: "example", wrong: "Yesterday I go to the mall and I buy shoes.", right: "Yesterday I went to the mall and bought shoes." },
        { type: "example", wrong: "I didn't went. Did you ate?", right: "I didn't go. Did you eat?", note: "did already carries the past" },
        { type: "example", wrong: "We buyed groceries and cooked dinner.", right: "We bought groceries and cooked dinner." },
        { type: "tips", items: [
          "High-frequency irregulars first: go/went, take/took, make/made, get/got, see/saw.",
          "After didn't/did: base verb — didn't go, didn't see, didn't have.",
          "One tense leak per story is normal; two or three breaks the listener's trust in your timeline.",
        ] },
      ],
      keyPhrases: ["It happened when...", "I ended up...", "The next day we...", "That's when I realized..."],
    },
  },
  {
    slug: "time-prepositions",
    courseSlug: "english-foundations",
    title: "Time prepositions: in, on, at",
    category: "grammar",
    level: "beginner",
    summary: "The funnel: IN a year, ON a day, AT a time.",
    durationMin: 6,
    orderIndex: 5,
    skillFocus: "grammar",
    content: {
      blocks: [
        { type: "concept", title: "The funnel", body: "AT for exact times (at 7:30, at noon, at night). ON for days and dates (on Friday, on my birthday). IN for months, years, seasons, long periods (in June, in 2026, in the evening)." },
        { type: "example", wrong: "I start work in 9 AM. See you on Monday morning — no wait, I leave in Monday.", right: "I start work at 9 AM. See you on Monday." },
        { type: "example", wrong: "We met on January and traveled in the Tuesday.", right: "We met in January and traveled on Tuesday." },
        { type: "tips", items: [
          "Exceptions to memorize: at night, in the morning/evening, on time, at the weekend (US: on the weekend).",
          "Place uses the same logic: at the bus stop (point), on the bus (surface), in the office (space).",
        ] },
      ],
      keyPhrases: ["at 9 sharp", "on Monday morning", "in the evening", "at night"],
    },
  },
  {
    slug: "negatives-that-sound-right",
    courseSlug: "english-foundations",
    title: "Negatives that sound right",
    category: "grammar",
    level: "beginner",
    summary: "One negative per sentence — no double negatives, no missing helpers.",
    durationMin: 5,
    orderIndex: 6,
    skillFocus: "grammar",
    content: {
      blocks: [
        { type: "concept", title: "Standard English keeps one negative", body: "I don't know anything (or: I know nothing — but never both). Helpers do/does/did make the negative: doesn't like, didn't see, can't wait. After don't/doesn't/didn't the main verb stays base: doesn't go, not doesn't goes." },
        { type: "example", wrong: "I don't know nothing about it.", right: "I don't know anything about it." },
        { type: "example", wrong: "He didn't told nobody.", right: "He didn't tell anybody." },
        { type: "tips", items: [
          "nobody/nothing/no one already negative — no second not.",
          "Any- words (anything, anyone, anywhere) live in negatives and questions.",
          "Positive forms: I know nothing. / Nobody told me.",
        ] },
      ],
      keyPhrases: ["I don't think so", "Not at all", "No idea", "It doesn't matter"],
    },
  },
  {
    slug: "countable-vs-uncountable",
    courseSlug: "english-foundations",
    title: "Countable vs. uncountable nouns",
    category: "grammar",
    level: "intermediate",
    summary: "information, advice, furniture — the nouns that never take a plural.",
    durationMin: 7,
    orderIndex: 7,
    skillFocus: "grammar",
    content: {
      blocks: [
        { type: "concept", title: "Can you put a number in front?", body: "If yes: two ideas, three reports (countable). If no: some information, much advice, a piece of furniture (uncountable). Uncountables never take -s or a/an: an information ✗, informations ✗." },
        { type: "example", wrong: "I have many informations for you.", right: "I have a lot of information for you." },
        { type: "example", wrong: "Can you give me an advice?", right: "Can you give me some advice? / a piece of advice?" },
        { type: "example", wrong: "He bought two breads.", right: "He bought two loaves of bread." },
        { type: "tips", items: [
          "The big ones: information, advice, news, furniture, luggage, equipment, homework, feedback.",
          "Use a lot of (not many) with uncountables; much mainly in negatives/questions.",
          "Turn them countable with pairings: an item of info, a piece of news.",
        ] },
      ],
      keyPhrases: ["some advice", "a lot of information", "piece of furniture", "much progress"],
    },
  },
  {
    slug: "questions-that-sound-right",
    courseSlug: "english-foundations",
    title: "Questions that sound right",
    category: "grammar",
    level: "intermediate",
    summary: "Yes/no questions need an auxiliary in front — and “I have a doubt” has a better version.",
    durationMin: 7,
    orderIndex: 8,
    skillFocus: "grammar",
    content: {
      blocks: [
        { type: "concept", title: "Invert or add a helper", body: "You are agree ✗ → Do you agree? Where you go ✗ → Where did you go? With be/modals the verb itself moves: Are you ready? Can you help? The same structure runs every meeting question." },
        { type: "example", wrong: "You are working from home today?", right: "Are you working from home today?" },
        { type: "example", wrong: "How you say this in English?", right: "How do you say this in English?" },
        { type: "example", wrong: "I have one doubt about the agenda.", right: "I have a question about the agenda.", note: "doubt = uncertainty; question = what you want clarified" },
        { type: "tips", items: [
          "Question words first, then helper, then subject: What + does + she + do?",
          "In meetings, “I have a question” or “Can I ask something?” both land well.",
          "Tag questions for soft checks: You've seen this, haven't you?",
        ] },
      ],
      keyPhrases: ["Could I ask something?", "I have a quick question", "How do you mean?", "Does that make sense?"],
    },
  },
  {
    slug: "comparisons-in-conversation",
    courseSlug: "english-foundations",
    title: "Comparisons in conversation",
    category: "grammar",
    level: "beginner",
    summary: "better than, the best — never “more better”.",
    durationMin: 5,
    orderIndex: 9,
    skillFocus: "grammar",
    content: {
      blocks: [
        { type: "concept", title: "Two systems, three levels", body: "Short adjectives (1-2 syllables): big → bigger → the biggest. Long adjectives: difficult → more difficult → the most difficult. Irregular: good/better/best, bad/worse/worst." },
        { type: "example", wrong: "This option is more better for the team.", right: "This option is better for the team." },
        { type: "example", wrong: "It was the most easiest exam.", right: "It was the easiest exam." },
        { type: "tips", items: [
          "as + base + as for equality: as fast as mine.",
          "Comparisons love data: 20% faster than last quarter.",
          "Say “the best” carefully in interviews — back it with a fact.",
        ] },
      ],
      keyPhrases: ["better than expected", "the best part was", "twice as fast as", "far more useful"],
    },
  },
  {
    slug: "conditionals-in-real-life",
    courseSlug: "english-foundations",
    title: "Conditionals in real life",
    category: "grammar",
    level: "intermediate",
    summary: "if + present for plans, if + past for dreams — no “would” in the if-clause.",
    durationMin: 7,
    orderIndex: 10,
    skillFocus: "grammar",
    content: {
      blocks: [
        { type: "concept", title: "Two conditionals you'll actually use", body: "First conditional (real future): If I get the offer, I will accept. Second conditional (unlikely/hypothetical): If I had more time, I would learn Japanese. “Would” belongs in the result half only." },
        { type: "example", wrong: "If I would have time, I will join the gym.", right: "If I have time, I will join the gym." },
        { type: "example", wrong: "If you would study harder, you would pass.", right: "If you studied harder, you would pass." },
        { type: "tips", items: [
          "Work talk runs on first conditionals: If we ship Friday, we'll hit the milestone.",
          "Dreams run on second conditionals: If I were you, I'd take the contract.",
          "“If I were you” is fixed — even for I/he/she.",
        ] },
      ],
      keyPhrases: ["If all goes well...", "Assuming that works...", "If I were you, I'd...", "Worst case, we..."],
    },
  },
  {
    slug: "word-order-fast",
    courseSlug: "english-foundations",
    title: "Word order at speed",
    category: "grammar",
    level: "intermediate",
    summary: "Adjective order, adverb placement — the rules you never learned but natives hear instantly.",
    durationMin: 6,
    orderIndex: 11,
    skillFocus: "grammar",
    content: {
      blocks: [
        { type: "concept", title: "Adjectives stack in a fixed order", body: "Opinion → size → age → shape → colour → origin → material → purpose: a beautiful small old round brown Indian wooden writing desk. You only need the first four slots in daily speech: a big red car, not a red big car." },
        { type: "example", wrong: "She drives a red big car.", right: "She drives a big red car." },
        { type: "example", wrong: "I only can speak English. I speak English only fluently.", right: "I can only speak English. / I speak only fluently." },
        { type: "tips", items: [
          "Adverbs of frequency (always, never) go BEFORE the main verb: I always forget.",
          "But AFTER be: She is always late.",
          "Only attaches to the word right after it: I only agreed (not “I agreed only”).",
        ] },
      ],
      keyPhrases: ["the only thing is", "always have been", "just about to", "still not sure"],
    },
  },
  {
    slug: "modals-with-confidence",
    courseSlug: "english-foundations",
    title: "Modals with confidence",
    category: "grammar",
    level: "beginner",
    summary: "can, should, must, could — bare verb after, no “to”, no -s.",
    durationMin: 5,
    orderIndex: 12,
    skillFocus: "grammar",
    content: {
      blocks: [
        { type: "concept", title: "Modals are followed by the bare verb", body: "I can drive (not can to drive / cans). He should come (not should comes). Ability: can/could. Advice: should/ought to. Necessity: must/have to. Possibility: might/could." },
        { type: "example", wrong: "You must to check this before sending.", right: "You must check this before sending." },
        { type: "example", wrong: "She can to handle the client call.", right: "She can handle the client call." },
        { type: "tips", items: [
          "Politeness ladder: can → could → would you mind + -ing.",
          "Soften advice with should / might want to / it might be worth + -ing.",
          "Past ability: could swim ≠ was able to finished (single completed event uses was able to).",
        ] },
      ],
      keyPhrases: ["I could help with that", "You might want to...", "That should work", "Would you mind...?"],
    },
  },
  {
    slug: "verb-patterns-that-matter",
    courseSlug: "english-foundations",
    title: "Verb patterns that matter",
    category: "grammar",
    level: "intermediate",
    summary: "enjoy doing vs. want to do — learn the verb WITH its pattern.",
    durationMin: 7,
    orderIndex: 13,
    skillFocus: "grammar",
    content: {
      blocks: [
        { type: "concept", title: "Two families", body: "-ING family: enjoy, avoid, keep, finish, mind, practice, suggest, recommend, consider, give up. TO family: want, decide, hope, plan, agree, promise, expect, refuse, offer, manage. Mix-ups are instantly noticeable." },
        { type: "example", wrong: "I enjoy to read after work.", right: "I enjoy reading after work." },
        { type: "example", wrong: "I want going home early.", right: "I want to go home early." },
        { type: "example", wrong: "We discussed about the timeline. Can you explain me the process?", right: "We discussed the timeline. Can you explain the process to me?" },
        { type: "tips", items: [
          "Discuss takes a direct object: discuss the budget (never discuss about).",
          "Explain: explain something TO someone.",
          "stop to do = pause in order to; stop doing = quit the habit.",
        ] },
      ],
      keyPhrases: ["I look forward to hearing", "I suggest starting", "I plan to", "It's worth checking"],
    },
  },
  {
    slug: "state-vs-action-verbs",
    courseSlug: "english-foundations",
    title: "State verbs vs. action verbs",
    category: "grammar",
    level: "intermediate",
    summary: "know, want, like stay simple — even when everything else is continuous.",
    durationMin: 5,
    orderIndex: 14,
    skillFocus: "grammar",
    content: {
      blocks: [
        { type: "concept", title: "No continuous forms for states", body: "Think/possess verbs describe a state, not an action in progress: know, want, need, like, love, hate, believe, own, belong, understand, seem, remember. Use I know, she wants — never I am knowing." },
        { type: "example", wrong: "I am knowing the answer.", right: "I know the answer." },
        { type: "example", wrong: "We are wanting an update.", right: "We want an update." },
        { type: "example", wrong: "I am having two siblings.", right: "I have two siblings.", note: "have = possession stays simple; have a shower = action, can be continuous" },
        { type: "tips", items: [
          "Tricky pairs: I think it's wrong (opinion, simple) vs. I'm thinking about it (considering, continuous).",
          "Same with see: I see your point vs. I'm seeing the doctor tomorrow.",
        ] },
      ],
      keyPhrases: ["I see what you mean", "I believe so", "That sounds right", "I'd love to"],
    },
  },
  {
    slug: "feelings-ed-vs-ing",
    courseSlug: "english-foundations",
    title: "Feelings: -ed vs. -ing",
    category: "grammar",
    level: "beginner",
    summary: "You are interested. The topic is interesting. Never swap them.",
    durationMin: 4,
    orderIndex: 15,
    skillFocus: "grammar",
    content: {
      blocks: [
        { type: "concept", title: "-ed = how you feel, -ing = what causes it", body: "People feel bored/tired/excited/confused. Books, movies and jobs are boring/tiring/exciting/confusing. The cause ends in -ing, the feeler ends in -ed." },
        { type: "example", wrong: "The lecture was bored. I am interesting in the topic.", right: "The lecture was boring. I am interested in the topic." },
        { type: "example", wrong: "This task is very confused.", right: "This task is very confusing." },
        { type: "tips", items: [
          "Same rule: surprising story / surprised reader; tiring day / tired worker.",
          "Interview trap: “I was exciting” → “I was excited about the challenge”.",
        ] },
      ],
      keyPhrases: ["I'm excited about", "That was exhausting", "It really surprised me", "I'm curious about"],
    },
  },
  {
    slug: "connectors-for-smooth-speech",
    courseSlug: "english-foundations",
    title: "Connectors for smooth speech",
    category: "grammar",
    level: "intermediate",
    summary: "Link two ideas without although...but, and without running out of breath.",
    durationMin: 6,
    orderIndex: 16,
    skillFocus: "grammar",
    content: {
      blocks: [
        { type: "concept", title: "One connector, one job", body: "Contrast: although / though / even though / however / on the other hand. Result: so / therefore / as a result. Reason: because / since / as. Never stack two contrast markers: although...but ✗." },
        { type: "example", wrong: "Although it was raining, but we went out.", right: "Although it was raining, we went out." },
        { type: "example", wrong: "Because the deadline moved, so we adjusted the plan.", right: "Because the deadline moved, we adjusted the plan." },
        { type: "tips", items: [
          "Speaking connectors (casual): so, but, actually, the thing is, that said.",
          "Writing connectors (formal): however, moreover, consequently, nevertheless.",
          "Start answers with: The main reason is... / What I'd add is... / That said, ...",
        ] },
      ],
      keyPhrases: ["That said,", "On top of that,", "As a result,", "The way I see it,"],
    },
  },
  {
    slug: "make-vs-do",
    courseSlug: "english-foundations",
    title: "Make vs. do",
    category: "vocabulary",
    level: "beginner",
    summary: "Collocations are half of sounding fluent — start with the make/do split.",
    durationMin: 5,
    orderIndex: 17,
    skillFocus: "vocabulary",
    content: {
      blocks: [
        { type: "concept", title: "CREATE vs. PERFORM", body: "MAKE = create/produce: make a mistake, make progress, make a decision, make coffee, make an effort. DO = perform/complete: do homework, do the dishes, do your best, do business, do a job (BrE)." },
        { type: "example", wrong: "I did a mistake in the report.", right: "I made a mistake in the report." },
        { type: "example", wrong: "Let me make my homework first.", right: "Let me do my homework first." },
        { type: "tips", items: [
          "Fixed: make sure, make sense, make a difference, do well, do you mind?",
          "Uncountable outputs take do: do the work, do research.",
          "Collocation habit: learn whole phrases, not single words.",
        ] },
      ],
      keyPhrases: ["make sense", "make sure", "do your best", "make a decision", "do the needful — avoid!"],
    },
  },
  {
    slug: "agreement-in-fast-speech",
    courseSlug: "english-foundations",
    title: "Agreement in fast speech",
    category: "grammar",
    level: "intermediate",
    summary: "he/she/it don't, everyone are — the errors that creep in when you speed up.",
    durationMin: 6,
    orderIndex: 18,
    skillFocus: "grammar",
    content: {
      blocks: [
        { type: "concept", title: "The verb follows the MAIN subject", body: "He/she/it + doesn't + base verb, and present verbs add -s: she goes, it costs. In longer sentences the verb still agrees with the head noun: the list...is, the team...has, each...takes." },
        { type: "example", wrong: "He don't agree with the plan. She go to gym daily.", right: "He doesn't agree with the plan. She goes to the gym daily." },
        { type: "example", wrong: "Everyone are welcome. Each of them have a copy.", right: "Everyone is welcome. Each of them has a copy." },
        { type: "example", wrong: "The list of items are ready.", right: "The list of items is ready." },
        { type: "tips", items: [
          "everyone/each/everybody/neither → singular verb.",
          "One of the students who ARE here (plural after “who” when the group is plural).",
          "Slowing down 10% fixes most agreement slips.",
        ] },
      ],
      keyPhrases: ["He doesn't seem to", "Everyone is on board", "Each of us has", "The team has agreed"],
    },
  },

  // ============================================================== speak-naturally
  {
    slug: "introduce-yourself-naturally",
    courseSlug: "speak-naturally",
    title: "Introduce yourself naturally",
    category: "conversation",
    level: "beginner",
    summary: "Three sentences that work in a lobby, a call, or an interview — without “myself...”.",
    durationMin: 5,
    orderIndex: 1,
    skillFocus: "speaking",
    content: {
      blocks: [
        { type: "concept", title: "Name + what you do + a hook", body: "Hi, I'm Rahul — I'm a data analyst at Acme. (name + role). Add one human hook: I've been building dashboards for three years, mostly for logistics teams. Never start with “Myself Rahul...” — that's a translated form." },
        { type: "example", wrong: "Myself Rahul, I am working in TCS from four years.", right: "I'm Rahul — I've been at TCS for four years." },
        { type: "example", wrong: "What is your good name?", right: "Sorry, I didn't catch your name." },
        { type: "dialogue", lines: [
          { speaker: "A", text: "Hi, I'm Priya. I work on the growth team at Loop." },
          { speaker: "B", text: "Nice to meet you — Samir. I do customer research, mostly remote." },
          { speaker: "A", text: "Small world, we're redoing our onboarding research this quarter." },
        ] },
        { type: "tips", items: [
          "Contract it: I'm / I've been / I work — full “I am” every sentence sounds robotic.",
          "Mirror the other person's length: 2-3 sentences for casual, 30-45 seconds for interviews.",
          "End with a hook or question so the other person can answer.",
        ] },
      ],
      keyPhrases: ["Hi, I'm...", "I've been ... for...", "I mostly work on...", "How about you?"],
    },
  },
  {
    slug: "sound-native-without-fillers",
    courseSlug: "speak-naturally",
    title: "Sound native without fillers",
    category: "conversation",
    level: "intermediate",
    summary: "Cut actually, basically, like, you know — replace them with structure.",
    durationMin: 7,
    orderIndex: 2,
    skillFocus: "fluency",
    content: {
      blocks: [
        { type: "concept", title: "Crutch words are habits, not vocabulary", body: "A filler every sentence makes fluent thoughts sound uncertain. The fix isn't silence training alone — it's having a starter you trust: The main point is... / What happened was... / The way I see it..." },
        { type: "example", wrong: "Actually I work in IT, and actually my team is remote.", right: "I work in IT, and my whole team is remote." },
        { type: "example", wrong: "It was like really like expensive.", right: "It was genuinely expensive." },
        { type: "tips", items: [
          "Record 60 seconds, count each crutch word, then redo the same answer.",
          "Replace “you know” with a tiny pause — silence reads as confidence.",
          "Vary openers: Actually / In fact / Honestly / To be honest (pick one per answer).",
        ] },
      ],
      keyPhrases: ["The main point is...", "What happened was...", "To be honest,", "In short,"],
    },
  },
  {
    slug: "pauses-that-sound-confident",
    courseSlug: "speak-naturally",
    title: "Pauses that sound confident",
    category: "conversation",
    level: "intermediate",
    summary: "Silent beats beat um and uh — and clause boundaries are where pauses belong.",
    durationMin: 6,
    orderIndex: 3,
    skillFocus: "fluency",
    content: {
      blocks: [
        { type: "concept", title: "Pause at boundaries, not mid-word", body: "The right places to pause: after your opener, between clauses, before a number. The wrong places: between an article and its noun (I went to the... market). Filled pauses (um, uh) signal searching; silent pauses signal thinking." },
        { type: "example", wrong: "Um, I think, uh, we should, uh, push the release.", right: "I think we should push the release. (beat) The main risk is QA time." },
        { type: "tips", items: [
          "Breathe at the comma, not at your memory's edge — chunk ideas into 4-6 word groups.",
          "If you lose a word, buy time once: Let me put it this way...",
          "Practice with numbers: they force pacing (the team grew from 12 to 40 in a year).",
        ] },
      ],
      keyPhrases: ["Let me put it this way...", "Two things: first...", "Here's the thing —", "What I mean is..."],
    },
  },
  {
    slug: "expand-your-sentence-range",
    courseSlug: "speak-naturally",
    title: "Expand your sentence range",
    category: "conversation",
    level: "intermediate",
    summary: "Escape the Subject-Verb-Object loop: because, although, which, when clauses on demand.",
    durationMin: 7,
    orderIndex: 4,
    skillFocus: "vocabulary",
    content: {
      blocks: [
        { type: "concept", title: "One idea, three shapes", body: "Level 1: The project finished late. Level 2: The project finished late because scope changed. Level 3: Although the deadline moved, the project finished late, which surprised the client. Each level adds one connector." },
        { type: "example", wrong: "The work is very busy. It is very long. It is very stressful.", right: "The work is intense, long, and often stressful." },
        { type: "tips", items: [
          "Swap repeated words for synonyms live: busy → hectic → demanding.",
          "Practice the because-although-which triple on any sentence you say today.",
          "Relative clauses start with who/which/that — the cheapest complexity upgrade.",
        ] },
      ],
      keyPhrases: ["which is why...", "even though...", "the reason I say that is...", "as someone who..."],
    },
  },
  {
    slug: "agreeing-and-disagreeing-smoothly",
    courseSlug: "speak-naturally",
    title: "Agreeing and disagreeing smoothly",
    category: "conversation",
    level: "intermediate",
    summary: "Vary your yes/no, and soften disagreement without disappearing.",
    durationMin: 6,
    orderIndex: 5,
    skillFocus: "confidence",
    content: {
      blocks: [
        { type: "concept", title: "Agreement has a spectrum", body: "Strong: Absolutely! / Exactly. Partial: I'd say so, mostly / I see it a bit differently. Disagree: I'm not sure I follow / That's one way to look at it — I'd add... Never open three answers in a row with plain Yes." },
        { type: "example", wrong: "Yes. Yes, I agree. Yes, that is right.", right: "That's right — and I'd add one caveat." },
        { type: "example", wrong: "No, you are wrong about that.", right: "I see your point — from my side, the data looked different." },
        { type: "dialogue", lines: [
          { speaker: "Manager", text: "Let's ship on Friday." },
          { speaker: "You", text: "I'd hold till Monday — QA hasn't cleared the payments flow yet." },
          { speaker: "Manager", text: "Fair. What if we cut scope instead?" },
          { speaker: "You", text: "That could work. If we drop the report screen, Friday is realistic." },
        ] },
        { type: "tips", items: [
          "Formula for soft disagreement: acknowledge + your view + question.",
          "In meetings, disagree with the idea, never the person.",
          "Close loops: Does that address your concern?",
        ] },
      ],
      keyPhrases: ["I'd say so, mostly", "I see your point, but...", "That's fair — and", "Can I push back gently?"],
    },
  },
  {
    slug: "sounding-confident-intonation",
    courseSlug: "speak-naturally",
    title: "Sounding confident: intonation",
    category: "pronunciation",
    level: "intermediate",
    summary: "Falling pitch for statements, rising for genuine questions — and why up-talk weakens you.",
    durationMin: 6,
    orderIndex: 6,
    skillFocus: "pronunciation",
    content: {
      blocks: [
        { type: "concept", title: "Where the pitch lands", body: "Statements fall at the end (I finished the report↘). Yes/no questions rise (You finished?↗). Wh-questions fall (When is the deadline?↘). If every statement rises, listeners keep waiting for the question." },
        { type: "example", wrong: "I led the migration? and it went fine?", right: "I led the migration, and it went fine." },
        { type: "tips", items: [
          "Stress the words that carry meaning: I finished it TODAY (not I FINished it today).",
          "List items rise until the last one, which falls: red, green, and blue↘.",
          "Record and listen: rising tails on statements are easy to spot once you know.",
        ] },
      ],
      keyPhrases: ["The deadline is Friday.", "That's the plan.", "Any questions?"],
    },
  },
  {
    slug: "intensifiers-without-overdoing",
    courseSlug: "speak-naturally",
    title: "Intensifiers without overdoing",
    category: "vocabulary",
    level: "intermediate",
    summary: "very good, really good, incredibly good — one per sentence, chosen precisely.",
    durationMin: 5,
    orderIndex: 7,
    skillFocus: "vocabulary",
    content: {
      blocks: [
        { type: "concept", title: "The intensifier ladder", body: "Neutral: very, quite. Strong: really, pretty (casual). Very strong: extremely, incredibly, absolutely (careful: extremely good is fine, extremely dead is comedy). With amount nouns use very much / how much — not very." },
        { type: "example", wrong: "The food was very much good. The design is too much good.", right: "The food was really good. The design is exceptionally good." },
        { type: "tips", items: [
          "very + adjective; very much + verb: I like it very much.",
          "Replace one very with a precise adjective: very tired → exhausted, very happy → thrilled.",
          "Absolutes never take very: can't say very perfect/unique/finished.",
        ] },
      ],
      keyPhrases: ["absolutely brilliant", "pretty good actually", "I'm thrilled", "not bad at all"],
    },
  },
  {
    slug: "th-sounds-in-everyday-words",
    courseSlug: "speak-naturally",
    title: "The th sounds",
    category: "pronunciation",
    level: "beginner",
    summary: "/θ/ and /ð/ — think and this — the two sounds that mark English instantly.",
    durationMin: 7,
    orderIndex: 8,
    skillFocus: "pronunciation",
    content: {
      blocks: [
        { type: "concept", title: "Tongue between the teeth", body: "Voiceless /θ/: think, three, through — air flows, no voice. Voiced /ð/: this, that, the — add voice. Tongue tip lightly touches the upper teeth edge; never substitute t or d (tink, dis)."},
        { type: "example", wrong: "I tink dis is de right tree.", right: "I think this is the right tree." },
        { type: "tips", items: [
          "Minimal pairs: think/tink, thick/tick, this/dis, breathe/breeze.",
          "Speed drill: thirty-three thieves thought about it.",
          "The gets stressed in sentences: THE deadline moved.",
        ] },
      ],
      keyPhrases: ["I think so", "this one", "three things", "through the process"],
    },
  },
  {
    slug: "w-vs-v-sounds",
    courseSlug: "speak-naturally",
    title: "w vs. v sounds",
    category: "pronunciation",
    level: "beginner",
    summary: "Teeth on lip for /v/, rounded lips for /w/ — want vs. vant, wine vs. vine.",
    durationMin: 6,
    orderIndex: 9,
    skillFocus: "pronunciation",
    content: {
      blocks: [
        { type: "concept", title: "Two mouth positions", body: "/v/ = upper teeth touch the lower lip, voice buzzes (very, voice, vital). /w/ = lips round, no teeth contact, quick glide (we, want, world). Swapping them changes words: vine vs. wine." },
        { type: "example", wrong: "I wery much want to werk with you.", right: "I very much want to work with you." },
        { type: "tips", items: [
          "Minimal pairs: very/wery, vet/wet, veto/wayto, vine/wine.",
          "Drill: Victor wasted a very warm winter.",
          "Watch your 'very' — it appears in every praise sentence.",
        ] },
      ],
      keyPhrases: ["very much", "we will", "our team", "value the work"],
    },
  },

  // ============================================================ workplace-english
  {
    slug: "emails-that-get-replies",
    courseSlug: "workplace-english",
    title: "Emails that get replies",
    category: "professional",
    level: "intermediate",
    summary: "Subject, ask, deadline — and why “kindly revert back” loses international readers.",
    durationMin: 9,
    orderIndex: 1,
    skillFocus: "writing",
    content: {
      blocks: [
        { type: "concept", title: "The 4-line email", body: "1) Context in one line. 2) The ask in bold. 3) Deadline. 4) Closing courtesy. Modern international English prefers Could you / Would you mind over Kindly, and get back to me over revert." },
        { type: "example", wrong: "Kindly do the needful and revert back to me at the earliest.", right: "Could you review the attached proposal and send comments by Thursday?" },
        { type: "example", wrong: "I am writing this mail to inform you that please find attached herewith the report.", right: "Attached is the Q3 report — the highlights are on page 2." },
        { type: "tips", items: [
          "Subject line = the ask: “Approval needed: vendor contract by Fri”.",
          "One email, one ask. Multiple asks get partial replies or none.",
          "Cut ceremonial openings: “Hope this email finds you well” → skip it.",
          "Attachments: mention them in the body text, not only as an attachment.",
        ] },
      ],
      keyPhrases: ["Could you ... by Thursday?", "Attaching the ... here.", "Happy to walk through it.", "Let me know if that works."],
    },
  },
  {
    slug: "meetings-voice-updates",
    courseSlug: "workplace-english",
    title: "Meetings & voice updates",
    category: "professional",
    level: "intermediate",
    summary: "Structure any spoken update in 20 seconds: status, blocker, ask.",
    durationMin: 7,
    orderIndex: 2,
    skillFocus: "speaking",
    content: {
      blocks: [
        { type: "concept", title: "Status → Blocker → Ask", body: "Standups and check-ins reward structure. “Where are we” + “what's in the way” + “what I need”. Twenty seconds, three parts, then stop talking." },
        { type: "dialogue", lines: [
          { speaker: "You", text: "Quick update from my side — the importer is done and tested." },
          { speaker: "You", text: "I'm blocked on staging access, so I can't verify the webhook flow." },
          { speaker: "You", text: "If DevOps can grant that today, I can close it by tomorrow noon." },
        ] },
        { type: "example", wrong: "So, actually, I was working on many things and it is going on...", right: "The importer is done; staging access is my blocker; grant that today and I'll close by tomorrow." },
        { type: "tips", items: [
          "Use signposts: Quick update / One blocker / My ask is...",
          "If you're interrupted, finish the sentence then reclaim: To finish my point...",
          "Mic etiquette: mute when not speaking, unmute BEFORE you start.",
        ] },
      ],
      keyPhrases: ["Quick update from my side", "I'm currently blocked on", "My ask is", "I'll take that offline"],
    },
  },
  {
    slug: "small-talk-that-works",
    courseSlug: "workplace-english",
    title: "Small talk that works",
    category: "conversation",
    level: "beginner",
    summary: "The two minutes before a call: weather, weekend, work context — with exit lines.",
    durationMin: 5,
    orderIndex: 3,
    skillFocus: "confidence",
    content: {
      blocks: [
        { type: "concept", title: "Open → share → hand back", body: "Open with a light observation (rough week for calls, isn't it?), share one line about yourself, then hand the ball back (how's your side?). Small talk is an exchange, not an interview." },
        { type: "dialogue", lines: [
          { speaker: "You", text: "Hey! How's your week going so far?" },
          { speaker: "Them", text: "Busy — we just moved the release up. You?" },
          { speaker: "You", text: "Same on our side. I'm juggling two launches. Anyway, shall we get into it?" },
        ] },
        { type: "tips", items: [
          "Safe topics: weekend plans, a shared meeting, travel, food, sports events.",
          "Skip politics, salary, and personal medical questions with strangers.",
          "Exit line: Anyway, shall we get started?",
        ] },
      ],
      keyPhrases: ["How's your week going?", "Long time no see —", "Busy on our side too", "Shall we get into it?"],
    },
  },

  // ========================================================= english-for-interviews
  {
    slug: "talk-about-your-education",
    courseSlug: "english-for-interviews",
    title: "Talk about your education",
    category: "interview",
    level: "beginner",
    summary: "Degree, institution, highlight — without “I passed out of...”.",
    durationMin: 5,
    orderIndex: 1,
    skillFocus: "speaking",
    content: {
      blocks: [
        { type: "concept", title: "Three beats, ten seconds", body: "I completed my [degree] at [institution] in [year], where I focused on [specialty/project]. Add one outcome if relevant: my final project became the basis of my first role." },
        { type: "example", wrong: "I passed out of Delhi University in 2020.", right: "I graduated from Delhi University in 2020." },
        { type: "example", wrong: "I have done B.Tech from IIT.", right: "I earned my B.Tech from IIT in 2021." },
        { type: "tips", items: [
          "graduate from / completed my ... at / earned my ... — all safe.",
          "Ongoing studies: I'm in my final year of ..., graduating next May.",
          "Switch quickly to what you did: projects, internships, roles.",
        ] },
      ],
      keyPhrases: ["I graduated from...", "I completed my ... at", "My focus was on...", "I'm in my final year of..."],
    },
  },
  {
    slug: "interview-story-method",
    courseSlug: "english-for-interviews",
    title: "The story method for interview answers",
    category: "interview",
    level: "intermediate",
    summary: "STAR that actually fits in 90 seconds: situation, task, action, result — with numbers.",
    durationMin: 8,
    orderIndex: 2,
    skillFocus: "confidence",
    content: {
      blocks: [
        { type: "concept", title: "90 seconds, four beats", body: "Situation (1 line) → Task (1 line) → Action (the bulk, what YOU did) → Result (number or observable outcome). “I” not “we” in the action half. Prepare three reusable stories." },
        { type: "dialogue", lines: [
          { speaker: "Interviewer", text: "Tell me about a time you handled a tight deadline." },
          { speaker: "You", text: "Our biggest client moved their launch up by two weeks — I owned the release checklist." },
          { speaker: "You", text: "I cut scope to the core flow, split QA into daily checkpoints, and paired with support on the comms." },
          { speaker: "You", text: "We shipped on the original date with zero P1s, and the client renewed for another year." },
        ] },
        { type: "tips", items: [
          "Open with the punchline if asked “biggest achievement”: Lead with the number.",
          "Failures: situation, what YOU did wrong, what you changed — 60% forward-looking.",
          "End every story with a number or a clear before/after.",
        ] },
      ],
      keyPhrases: ["The situation was...", "My job was to...", "What I did first was", "As a result, we..."],
    },
  },

  // ============================================================ advanced-vocabulary
  {
    slug: "collocations-for-impact",
    courseSlug: "advanced-vocabulary",
    title: "Collocations for impact",
    category: "vocabulary",
    level: "advanced",
    summary: "Strong verbs + precise nouns: raise a concern, not “make a concern”.",
    durationMin: 8,
    orderIndex: 1,
    skillFocus: "vocabulary",
    content: {
      blocks: [
        { type: "concept", title: "Words travel in pairs", body: "Fluency is mostly collocation knowledge: raise a concern, meet expectations, drive growth, bear in mind, a heavy workload, a compelling case. Learning single words gives you nouns; learning pairs gives you sentences." },
        { type: "example", wrong: "We did a meeting about the budget and did some discussion.", right: "We held a meeting to discuss the budget." },
        { type: "example", wrong: "The results were very much improved.", right: "The results improved markedly." },
        { type: "tips", items: [
          "Verb + noun: make a decision, take responsibility, keep pace, set the tone.",
          "Adj + noun: critical feedback, keen interest, stark contrast, remote work.",
          "Learn 5 collocations per topic, not 20 loose words.",
        ] },
      ],
      keyPhrases: ["raise a concern", "meet expectations", "bear in mind", "a compelling case", "move the needle"],
    },
  },
  {
    slug: "precision-words-for-essays",
    courseSlug: "advanced-vocabulary",
    title: "Precision words for essays",
    category: "vocabulary",
    level: "advanced",
    summary: "Swap vague intensifiers for exact words: rampant, marginal, pivotal, detrimental.",
    durationMin: 7,
    orderIndex: 2,
    skillFocus: "vocabulary",
    content: {
      blocks: [
        { type: "concept", title: "Specific beats strong", body: "“Very bad” becomes detrimental, harmful, severe. “Big improvement” becomes substantial, marked, a leap. Precision words earn credibility — but one per sentence, never stacked." },
        { type: "example", wrong: "Social media is very much bad for attention and very big problem.", right: "Unchecked social media use is detrimental to sustained attention." },
        { type: "tips", items: [
          "Academic trio: however (contrast), moreover (add), therefore (result) — one per paragraph.",
          "Hedge properly: suggests, tends to, appears to — overclaiming weakens essays.",
          "Keep a personal word bank of 3 replacements per vague adjective.",
        ] },
      ],
      keyPhrases: ["on the other hand", "a pivotal factor", "marginally better", "detrimental to", "the evidence suggests"],
    },
  },
];
