import type { MistakeSeed } from "./types";

/**
 * Mistake catalog. Every entry is understood by the analyzer through
 * `detection` (regex patterns, filler rules, fluency metrics or
 * pronunciation hints) and by the practice engine through `practicePrompts`.
 */
export const mistakes: MistakeSeed[] = [
  // ------------------------------------------------------------------ grammar
  {
    key: "since-for",
    title: "Using “since” with a duration",
    category: "grammar",
    subcategory: "prepositions",
    description: "“Since” marks a starting point, “for” marks a length of time.",
    wrongExample: "I am working here since 3 years.",
    correctExample: "I have been working here for 3 years.",
    why: "“Since” answers WHEN something started (since 2023, since Monday). “For” answers HOW LONG it has continued (for 3 years, for a week). A duration like “3 years” always takes “for”.",
    naturalAlternative: "I've been working here for three years.",
    severity: "medium",
    lessonSlug: "since-vs-for",
    practicePrompts: [
      "Talk about how long you have lived in your city.",
      "Describe how long you have been at your current job.",
      "Explain how long you have been learning English.",
      "Say how long you have known your best friend.",
    ],
    detection: { kind: "regex", patterns: ["\\bsince\\s+(\\d+|a|one|two|three|four|five|six|seven|eight|nine|ten|many|few|several)\\s+(year|month|week|day|hour|minute)s?\\b"] },
  },
  {
    key: "present-perfect-continuous",
    title: "Missing “have been + -ing” for ongoing actions",
    category: "grammar",
    subcategory: "tenses",
    description: "Actions that started in the past and continue now use “have/has been + verb-ing”.",
    wrongExample: "I am working here since 2023.",
    correctExample: "I have been working here since 2023.",
    why: "“I am working” describes right now only. When the action began earlier and continues, English uses the present perfect continuous: have/has + been + verb-ing.",
    naturalAlternative: "I've been working here since 2023.",
    severity: "high",
    lessonSlug: "talking-about-ongoing-life",
    practicePrompts: [
      "Describe what you have been doing this week.",
      "Talk about a hobby you have been doing for years.",
      "Explain what you have been working on lately.",
    ],
    detection: { kind: "regex", patterns: ["\\bi\\s+am\\s+\\w+ing\\s+since\\b", "\\bhe\\s+is\\s+\\w+ing\\s+since\\b", "\\bshe\\s+is\\s+\\w+ing\\s+since\\b", "\\bwe\\s+are\\s+\\w+ing\\s+since\\b", "\\bthey\\s+are\\s+\\w+ing\\s+since\\b"] },
  },
  {
    key: "article-a-an",
    title: "Wrong a/an choice",
    category: "grammar",
    subcategory: "articles",
    description: "Use “an” before a vowel SOUND, “a” before a consonant sound.",
    wrongExample: "She is a honest person. I bought a apple.",
    correctExample: "She is an honest person. I bought an apple.",
    why: "The choice depends on sound, not spelling: “honest” starts with a vowel sound, so it takes “an”. Words like “university” start with a “y” sound, so they take “a”.",
    severity: "low",
    lessonSlug: "articles-that-sound-right",
    practicePrompts: [
      "Introduce three things on your desk using a/an.",
      "Describe your morning routine using a and an correctly.",
    ],
    detection: { kind: "regex", patterns: ["\\ba\\s+(apple|egg|orange|idea|issue|answer|example|hour|honest|umbrella|university\\b|x\\b)", "\\ban\\s+(book|car|house|phone|table|girl|boy|man|woman|university|user|one|unit|european)\\b"] },
  },
  {
    key: "article-the-missing",
    title: "Missing “the” for known things",
    category: "grammar",
    subcategory: "articles",
    description: "Places you go to regularly or things already mentioned take “the”.",
    wrongExample: "I went to market yesterday. He is in office.",
    correctExample: "I went to the market yesterday. He is in the office.",
    why: "When both speakers know which place you mean (your usual market, the office you both know), English uses “the”. Compare: “go to work/school/home” (no article) with “go to the office/the market/the bank”.",
    naturalAlternative: "I went to the market yesterday.",
    severity: "medium",
    lessonSlug: "articles-that-sound-right",
    practicePrompts: [
      "Describe where you went yesterday using “the” correctly.",
      "Talk about your typical day at work or school.",
    ],
    detection: { kind: "regex", patterns: ["\\bwent\\s+to\\s+(market|office|school\\b|hospital\\b|station\\b|airport\\b)", "\\bin\\s+office\\b", "\\bat\\s+market\\b", "\\bgo\\s+to\\s+market\\b", "\\bhe\\s+is\\s+in\\s+office\\b"] },
  },
  {
    key: "article-unneeded",
    title: "Unnecessary “the”",
    category: "grammar",
    subcategory: "articles",
    description: "Days, years and many general places never take “the”.",
    wrongExample: "I will call you in the evening every day. We met in the 2020.",
    correctExample: "I will call you in the evening. We met in 2020.",
    why: "“In the evening” is fine, but calendars, years and general time words (yesterday, today, next week, 2020) never take an article.",
    severity: "low",
    lessonSlug: "articles-that-sound-right",
    practicePrompts: ["Talk about your plans for the coming week.", "Describe what you did yesterday and last year."],
    detection: { kind: "regex", patterns: ["\\bin\\s+the\\s+(yesterday|today|monday|tuesday|wednesday|thursday|friday|saturday|sunday|20\\d\\d)\\b", "\\bat\\s+the\\s+school\\b", "\\bon\\s+the\\s+monday\\b"] },
  },
  {
    key: "article-meal",
    title: "Article before meals",
    category: "grammar",
    subcategory: "articles",
    description: "Meals (breakfast, lunch, dinner) don’t take “a” or “the” in everyday phrases.",
    wrongExample: "Let's have a dinner. After the lunch we talked.",
    correctExample: "Let's have dinner. After lunch we talked.",
    why: "“Have/eat/serve + meal” is a fixed pattern without an article: have dinner, after lunch, before breakfast.",
    severity: "low",
    lessonSlug: "articles-that-sound-right",
    practicePrompts: ["Describe your family's dinner habits.", "Talk about what you do after lunch."],
    detection: { kind: "regex", patterns: ["\\b(a|the)\\s+(dinner|lunch|breakfast)\\b"] },
  },
  {
    key: "subject-verb-agreement",
    title: "He/She/It don’t — verb doesn’t agree",
    category: "grammar",
    subcategory: "agreement",
    description: "Third-person singular subjects take “doesn’t/don’t” and “-s” forms correctly.",
    wrongExample: "He don't like coffee. She go to gym every day.",
    correctExample: "He doesn't like coffee. She goes to the gym every day.",
    why: "He, she and it always take “does/doesn’t” and a verb ending in -s in the present tense: she goes, he works, it costs.",
    severity: "high",
    lessonSlug: "agreement-in-fast-speech",
    practicePrompts: [
      "Describe your boss or teacher in three sentences.",
      "Talk about what your family members do every day.",
    ],
    detection: { kind: "regex", patterns: ["\\b(he|she|it)\\s+don't\\b", "\\b(he|she|it)\\s+do\\s+not\\b", "\\b(he|she|it)\\s+go\\s+(to|at|every|each)\\b", "\\b(he|she|it)\\s+(work|live|eat|drink|like|want|need|take|make|come|have)\\s+(every|each|\\.\\.\\.|usually|often|always)\\b"] },
  },
  {
    key: "tense-shift",
    title: "Shifting tenses mid-story",
    category: "grammar",
    subcategory: "tenses",
    description: "A past-tense story should stay in the past tense.",
    wrongExample: "Yesterday I go to the market and I buy some fruits.",
    correctExample: "Yesterday I went to the market and bought some fruits.",
    why: "Once you start a story in the past (“yesterday”), every action in that story stays past: went, bought, paid, came back.",
    naturalAlternative: "Yesterday I went to the market and picked up some fruit.",
    severity: "high",
    lessonSlug: "past-tense-while-speaking",
    practicePrompts: [
      "Describe your last weekend from Saturday morning to Sunday night.",
      "Tell the story of how you got your current job or course.",
      "Explain what you did last holiday.",
    ],
    detection: { kind: "regex", patterns: ["\\b(yesterday|last\\s+(night|week|month|year|weekend))\\b[^.]{0,80}\\b\\b(go|come|buy|eat|see|meet|take|make|call|say|tell|get|have|was|were)\\b(?!\\s+(to\\s+have|been|s))"] },
  },
  {
    key: "irregular-past",
    title: "Irregular past forms (buyed, eated, teached)",
    category: "grammar",
    subcategory: "tenses",
    description: "Common irregular verbs don’t take -ed.",
    wrongExample: "I buyed a phone. We teached them.",
    correctExample: "I bought a phone. We taught them.",
    why: "About 200 common verbs are irregular: buy→bought, eat→ate, teach→taught, go→went, take→took. These carry most of daily conversation, so they need direct memorisation.",
    severity: "medium",
    lessonSlug: "past-tense-while-speaking",
    practicePrompts: [
      "Talk about what you bought last month.",
      "Describe a meal you cooked recently.",
    ],
    detection: { kind: "regex", patterns: ["\\b(boughted|buyed|eated|teached|goed|comed|taked|maked|seed|meeted|saids|getted|haved|wented|runned|writed|speaked|choosed)\\b"] },
  },
  {
    key: "did-past",
    title: "did + past form (didn’t went)",
    category: "grammar",
    subcategory: "tenses",
    description: "After “did/didn’t”, use the base verb.",
    wrongExample: "I didn't went home. Did you ate?",
    correctExample: "I didn't go home. Did you eat?",
    why: "“Did” already carries the past tense, so the main verb stays in its base form: didn’t go, didn’t eat, didn’t see.",
    severity: "high",
    lessonSlug: "past-tense-while-speaking",
    practicePrompts: [
      "Talk about three things you didn't do yesterday.",
      "Ask someone about their weekend using Did you...?",
    ],
    detection: { kind: "regex", patterns: ["\\bdidn't\\s+(went|ate|saw|came|took|made|got|had|was|were|bought|said|told|gave|felt|knew|thought)\\b", "\\bdid\\s+\\w+\\s+(went|ate|saw|came|took|made|got|had|bought)\\b"] },
  },
  {
    key: "preposition-time",
    title: "Wrong time preposition (in/on/at)",
    category: "grammar",
    subcategory: "prepositions",
    description: "in for months/years/long periods, on for days/dates, at for clock times.",
    wrongExample: "I wake up in 7 o'clock. We met on January. See you in Monday.",
    correctExample: "I wake up at 7 o'clock. We met in January. See you on Monday.",
    why: "Think of a funnel: IN a year → ON a day → AT a time. In 2026, on Friday, at 6:30.",
    severity: "medium",
    lessonSlug: "time-prepositions",
    practicePrompts: [
      "Describe your typical weekday schedule with exact times.",
      "Talk about plans for next month and next Monday.",
    ],
    detection: { kind: "regex", patterns: ["\\bin\\s+\\d{1,2}\\s*o'?clock\\b", "\\bat\\s+(monday|tuesday|wednesday|thursday|friday|saturday|sunday)\\b", "\\bon\\s+(january|february|march|april|may|june|july|august|september|october|november|december)\\b", "\\bon\\s+\\d{4}\\b", "\\bin\\s+(monday|tuesday|wednesday|thursday|friday)\\b", "\\bat\\s+(january|february|march|april)\\b"] },
  },
  {
    key: "preposition-place",
    title: "Wrong place preposition (in/on/at)",
    category: "grammar",
    subcategory: "prepositions",
    description: "in for enclosed spaces, on for surfaces, at for points/locations.",
    wrongExample: "I am waiting in the bus stop. She is on the office.",
    correctExample: "I am waiting at the bus stop. She is at the office.",
    why: "Think of a point: AT the bus stop (a location), ON the bus (a surface you stand on), IN the office (inside a room).",
    severity: "medium",
    lessonSlug: "time-prepositions",
    practicePrompts: ["Describe where your friends are right now.", "Give directions from your home to a nearby shop."],
    detection: { kind: "regex", patterns: ["\\bin\\s+the\\s+(bus stop|bus\\b|station\\b|airport\\b|queue\\b)", "\\bon\\s+the\\s+(office\\b|home\\b|school\\b|meeting\\b)", "\\bat\\s+the\\s+(home\\b|table\\s+in|bed\\b)"] },
  },
  {
    key: "double-negative",
    title: "Double negatives (I don’t know nothing)",
    category: "grammar",
    subcategory: "agreement",
    description: "Standard English uses one negative, not two.",
    wrongExample: "I don't know nothing. He didn't tell nobody.",
    correctExample: "I don't know anything. He didn't tell anybody.",
    why: "Two negatives cancel each other logically (“I don’t know nothing” literally means you know something). Standard English keeps one: don’t know anything / know nothing.",
    severity: "medium",
    lessonSlug: "negatives-that-sound-right",
    practicePrompts: ["Explain what you don't like about your routine.", "Talk about things you haven't done this month."],
    detection: { kind: "regex", patterns: ["\\b(don't|doesn't|didn't|can't|won't|couldn't|wouldn't|shouldn't|isn't|aren't|wasn't|weren't)\\s+(nothing|nobody|none|nowhere|never|no\\s+one)\\b"] },
  },
  {
    key: "countable-uncountable",
    title: "Countable/uncountable mix-ups",
    category: "grammar",
    subcategory: "nouns",
    description: "Some nouns can’t be counted and never take a plural or “many”.",
    wrongExample: "I have many informations. Can you give me an advice? He bought two breads.",
    correctExample: "I have a lot of information. Can you give me some advice? He bought two loaves of bread.",
    why: "Information, advice, news, furniture, luggage, bread are uncountable: no -s, no “a/an”, no “many”. Use “much/a lot of/some”, or countable pairings: an item of information, a piece of advice.",
    severity: "medium",
    lessonSlug: "countable-vs-uncountable",
    practicePrompts: [
      "Ask for advice about learning English.",
      "Describe the luggage you would pack for a trip.",
    ],
    detection: { kind: "regex", patterns: ["\\bmanys?\\s+(information|advice|news|furniture|luggage|bread|equipment|homework|knowledge|research|progress)\\b", "\\ban\\s+(information|advice|news|furniture|luggage|bread|equipment|homework|feedback)\\b", "\\b(two|three|four|several|few)\\s+(informations|advices|news|furnitures|luggages|breads|equipments|homeworks|softwares| equipments)\\b", "\\b(some|much|many)\\s+(equipment|homework|luggage|furniture)\\b"] },
  },
  {
    key: "plural-agreement",
    title: "Subject made of many parts takes a singular verb",
    category: "grammar",
    subcategory: "agreement",
    description: "“The list of...”, “one of the...”, “everyone” take singular verbs.",
    wrongExample: "The list of items are long. Everyone are welcome. Each of them have a copy.",
    correctExample: "The list of items is long. Everyone is welcome. Each of them has a copy.",
    why: "The verb agrees with the MAIN subject, not the nearest noun: the list...is, everyone...is, each...has. After “one of the X who...”, the verb is plural (one of the students who ARE).",
    severity: "medium",
    lessonSlug: "agreement-in-fast-speech",
    practicePrompts: ["Describe a team you belong to.", "Talk about the people in your household."],
    detection: { kind: "regex", patterns: ["\\b(everyone|everybody|someone|somebody|nobody|each|neither)\\s+(are|were|have|had|do)\\b", "\\b(the\\s+\\w+\\s+of\\s+\\w+\\s+)(are|were|have|do)\\b"] },
  },
  {
    key: "question-form",
    title: "Missing helper in questions",
    category: "grammar",
    subcategory: "questions",
    description: "Yes/no questions need do/does/did or an auxiliary before the subject.",
    wrongExample: "You are agree with me? How you say this in English? Where you go yesterday?",
    correctExample: "Do you agree with me? How do you say this in English? Where did you go yesterday?",
    why: "English questions invert the auxiliary and subject: Do you...? Does she...? Did they...? With be/have/modals, the verb itself moves: Are you...? Can you...?",
    severity: "high",
    lessonSlug: "questions-that-sound-right",
    practicePrompts: [
      "Ask five questions about someone's daily routine.",
      "Interview an imaginary colleague about their work.",
    ],
    detection: { kind: "regex", patterns: ["\\b(how|where|when|why|what|who)\\s+(you|we|they|he|she|it|i)\\s+(go|come|say|make|do|have|want|like|feel|think|need|know|work|live)\\b(?!\\s+(to|ing|ed|s)\\b)", "\\byou\\s+(are|is|can|will|should|would|do|did|have|had)\\s+(agree|know|think|want|like|mean|finish|understand)\\b"] },
  },
  {
    key: "comparative-superlative",
    title: "Double comparatives (more better, most easiest)",
    category: "grammar",
    subcategory: "word-form",
    description: "Use either -er/more, never both.",
    wrongExample: "This is more better. She is the most easiest person.",
    correctExample: "This is better. She is the easiest person.",
    why: "Short adjectives take -er/-est (easier, easiest); long adjectives take more/most (more difficult, most difficult). irregular: good→better→best, bad→worse→worst.",
    severity: "low",
    lessonSlug: "comparisons-in-conversation",
    practicePrompts: ["Compare your current city with your hometown.", "Compare two things you use daily."],
    detection: { kind: "regex", patterns: ["\\bmore\\s+(better|worse|easier|harder|faster|slower|bigger|smaller|greater|lesser)\\b", "\\bmost\\s+(easiest|hardest|fastest|slowest|biggest|smallest|best|worst)\\b", "\\bmore\\s+\\w+er\\b", "\\bless\\s+(more|better)\\b"] },
  },
  {
    key: "conditional-would",
    title: "If + would",
    category: "grammar",
    subcategory: "conditionals",
    description: "“Would” doesn’t go in the if-clause of a first conditional.",
    wrongExample: "If I would have time, I will come. If you would study, you would pass.",
    correctExample: "If I have time, I will come. If you studied, you would pass.",
    why: "The if-clause takes present tense (first conditional: If I have...I will...) or past tense (second: If I had...I would...). “Would” only appears in the result half (or in polite requests).",
    severity: "medium",
    lessonSlug: "conditionals-in-real-life",
    practicePrompts: [
      "Talk about what you will do if you get more free time.",
      "Describe what you would change about your city.",
    ],
    detection: { kind: "regex", patterns: ["\\bif\\s+\\w+\\s+would\\b"] },
  },
  {
    key: "adjective-order",
    title: "Adjective order (a red big car)",
    category: "grammar",
    subcategory: "word-order",
    description: "Opinion → size → age → shape → colour → origin → material → purpose.",
    wrongExample: "She bought a red big car. It is a cotton beautiful shirt.",
    correctExample: "She bought a big red car. It is a beautiful cotton shirt.",
    why: "Native speakers follow an unwritten order without thinking: opinion (beautiful) before size (big) before colour (red) before material (cotton). Breaking it sounds noticeably foreign.",
    severity: "low",
    lessonSlug: "word-order-fast",
    practicePrompts: ["Describe three objects in your room.", "Describe your dream house."],
    detection: { kind: "regex", patterns: ["\\b(red|blue|green|black|white|yellow|brown|pink)\\s+(big|small|large|little|old|new|tall|long|short)\\s+(car|house|dog|cat|bag|shirt|table|phone)\\b", "\\b(cotton|wooden|plastic|metal|silk)\\s+(beautiful|nice|good|lovely|pretty|amazing|great)\\b"] },
  },
  {
    key: "modal-gerund",
    title: "can to drive / must to go",
    category: "grammar",
    subcategory: "modals",
    description: "Modals take the bare verb: can drive, must go, should try.",
    wrongExample: "I can to drive. You must to check this. She should to come early.",
    correctExample: "I can drive. You must check this. She should come early.",
    why: "After can, could, may, might, must, shall, should, will, would, have to — the verb has no “to” and no -s: he can go (not he can to go / he cans).",
    severity: "medium",
    lessonSlug: "modals-with-confidence",
    practicePrompts: ["Explain what you can and can't do at work.", "Give advice to a friend using should."],
    detection: { kind: "regex", patterns: ["\\b(can|could|may|might|must|shall|should|will|would|ought)\\s+to\\s+\\w+\\b"] },
  },
  {
    key: "gerund-vs-infinitive",
    title: "enjoy to play / I want going",
    category: "grammar",
    subcategory: "verb-patterns",
    description: "Some verbs take -ing, others take to + verb.",
    wrongExample: "I enjoy to read. I want going home. I suggest to wait.",
    correctExample: "I enjoy reading. I want to go home. I suggest waiting.",
    why: "enjoy, avoid, suggest, keep, finish, mind, practice, give up + -ing. want, decide, hope, plan, agree, promise, suggest (a thing to do) + to + verb. Learn each verb with its pattern.",
    severity: "medium",
    lessonSlug: "verb-patterns-that-matter",
    practicePrompts: ["Talk about what you enjoy doing after work.", "Describe your plans for next month."],
    detection: { kind: "regex", patterns: ["\\b(enjoy|avoid|suggest|keep|finish|mind|practice|continue|consider|recommend|postpone|give up|can't help)\\s+to\\s+\\w+\\b", "\\b(want|decide|hope|plan|agree|promise|expect|refuse|offer|manage|afford|pretend|tend)\\s+\\w+ing\\b"] },
  },
  {
    key: "stative-verb",
    title: "I am knowing / I am wanting",
    category: "grammar",
    subcategory: "tenses",
    description: "State verbs (know, want, like, need, own) don’t use continuous forms.",
    wrongExample: "I am knowing the answer. She is wanting a new phone.",
    correctExample: "I know the answer. She wants a new phone.",
    why: "Verbs of thinking and possession describe a state, not an action in progress: know, want, need, like, love, hate, believe, own, belong, seem, understand. They stay in simple tenses.",
    severity: "medium",
    lessonSlug: "state-vs-action-verbs",
    practicePrompts: ["Say what you know about your city.", "Describe what you want from your career."],
    detection: { kind: "regex", patterns: ["\\b(am|is|are)\\s+(knowing|wanting|needing|liking|loving|hating|believing|owning|belonging|seeming|understanding|remembering|forgetting|possessing)\\b"] },
  },
  {
    key: "ed-ing-adjective",
    title: "I am interesting / it is bored",
    category: "grammar",
    subcategory: "word-form",
    description: "-ed adjectives describe how you feel, -ing adjectives describe what causes the feeling.",
    wrongExample: "The movie was bored. I am interesting in music.",
    correctExample: "The movie was boring. I am interested in music.",
    why: "People are interested/excited/tired/bored; things are interesting/exciting/tiring/boring. The feeling is -ed, the source is -ing.",
    severity: "medium",
    lessonSlug: "feelings-ed-vs-ing",
    practicePrompts: ["Review a movie or series you watched.", "Describe what bores and interests you."],
    detection: { kind: "regex", patterns: ["\\bi\\s+am\\s+(interesting|boring|tiring|exciting|confusing|surprising|annoying|frustrating)\\b", "\\b(the|this|that|it|movie|book|class|lecture|game)\\s+(was|is|are)\\s+(bored|interested|excited|tired|confused|surprised|annoyed|frustrated)\\b", "\\bmake\\s+me\\s+(to\\s+)?(interesting|boring|exciting)\\b"] },
  },
  {
    key: "although-but",
    title: "although... but",
    category: "grammar",
    subcategory: "connectors",
    description: "“Although” already means “but” — never use both.",
    wrongExample: "Although it was raining, but we went out.",
    correctExample: "Although it was raining, we went out. It was raining, but we went out.",
    why: "“Although” and “but” both mark contrast. Using them together repeats the idea: choose one. Same rule for because...so and because...why.",
    severity: "low",
    lessonSlug: "connectors-for-smooth-speech",
    practicePrompts: ["Explain why you chose your job or course despite difficulties."],
    detection: { kind: "regex", patterns: ["\\balthough\\b[^.]{0,80}\\bbut\\b", "\\bbecause\\b[^.]{0,80}\\bso\\s+(i|we|they|he|she)\\b"] },
  },
  {
    key: "discuss-about",
    title: "discuss about / explain me",
    category: "grammar",
    subcategory: "verb-patterns",
    description: "“Discuss” never takes “about”; “explain” takes “to someone”.",
    wrongExample: "We discussed about the project. Can you explain me this?",
    correctExample: "We discussed the project. Can you explain this to me?",
    why: "Discuss is transitive: discuss the project, discuss plans (no preposition). Explain is explain + thing + TO + person: explain it to me, not explain me it.",
    severity: "medium",
    lessonSlug: "verb-patterns-that-matter",
    practicePrompts: ["Describe a discussion you had at work this week.", "Ask someone to explain a concept to you."],
    detection: { kind: "regex", patterns: ["\\bdiscuss\\s+about\\b", "\\bexplain\\s+(me|us|him|her|them)\\s+(?!to)\\b"] },
  },
  {
    key: "made-mistake",
    title: "do a mistake",
    category: "vocab",
    subcategory: "collocations",
    description: "We MAKE mistakes, not do them.",
    wrongExample: "Sorry, I did a mistake.",
    correctExample: "Sorry, I made a mistake.",
    why: "English pairs certain verbs with certain nouns: make a mistake, make progress, make an effort, do homework, do business, do your best.",
    severity: "low",
    lessonSlug: "make-vs-do",
    practicePrompts: ["Talk about a mistake you learned from.", "Describe your progress this month."],
    detection: { kind: "regex", patterns: ["\\bdid\\s+a\\s+mistake\\b", "\\bdo\\s+(a\\s+mistake|an\\s+error|the\\s+mistake)\\b", "\\bmake\\s+(homework|business|a\\s+favour\\s+to)\\b"] },
  },
  // ------------------------------------------------------- naturalness / style
  {
    key: "question-doubt",
    title: "I have a doubt → I have a question",
    category: "naturalness",
    subcategory: "word-choice",
    description: "In everyday English, questions are “questions”, not “doubts”.",
    wrongExample: "I have one doubt about the report.",
    correctExample: "I have a question about the report.",
    why: "“Doubt” in English usually means uncertainty or disbelief (I doubt it). For something you want clarified, say question, query (formal) or point (in meetings). “I have a doubt” reads as translated speech.",
    naturalAlternative: "Can I ask something about the report?",
    severity: "medium",
    lessonSlug: "questions-that-sound-right",
    practicePrompts: [
      "Ask three questions about this app.",
      "In a meeting, raise a question about a decision.",
    ],
    detection: { kind: "regex", patterns: ["\\b(i|we|he|she|they)\\s+have\\s+(a|one|some|doubts|two)\\s+doubts?\\b", "\\bmy\\s+doubt\\s+is\\b", "\\bclear\\s+(my|the|our)\\s+doubts?\\b"] },
  },
  {
    key: "revert-back",
    title: "revert back",
    category: "style",
    subcategory: "professional",
    description: "“Revert” already means go back — “revert back” is redundant.",
    wrongExample: "Please revert back to me by Friday.",
    correctExample: "Please get back to me by Friday.",
    why: "Revert = return to a previous state. In Indian professional English it often means “reply”, but internationally it sounds redundant. Use reply, respond, get back to me, circle back.",
    naturalAlternative: "Could you send me your thoughts by Friday?",
    severity: "medium",
    lessonSlug: "emails-that-get-replies",
    practicePrompts: ["Write a short email asking for a reply by Friday.", "Follow up politely on an unanswered email."],
    detection: { kind: "regex", patterns: ["\\brevert\\s+back\\b", "\\bkindly\\s+revert\\b", "\\bplease\\s+revert\\b"] },
  },
  {
    key: "do-the-needful",
    title: "do the needful",
    category: "style",
    subcategory: "professional",
    description: "“Do the needful” is understood but sounds dated outside South Asia.",
    wrongExample: "Kindly do the needful and update me.",
    correctExample: "Please review the attached file and let me know.",
    why: "“Do the needful” is a colonial-era leftover. International teams expect a specific instruction: what to do, by when, and how you’ll know it’s done.",
    naturalAlternative: "Could you take care of the invoice and confirm once it's sent?",
    severity: "medium",
    lessonSlug: "emails-that-get-replies",
    practicePrompts: ["Ask a colleague to complete a specific task with a deadline."],
    detection: { kind: "regex", patterns: ["\\bdo\\s+the\\s+needful\\b", "\\bdoing\\s+the\\s+needful\\b"] },
  },
  {
    key: "myself-intro",
    title: "Myself Rahul — wrong introduction",
    category: "style",
    subcategory: "fluency",
    description: "Introduce yourself with “I’m...” or “My name is...”, not “Myself...”.",
    wrongExample: "Myself Rahul, I am working at TCS.",
    correctExample: "I'm Rahul, and I work at TCS.",
    why: "“Myself” is a reflexive pronoun (I hurt myself) or an intensifier (I myself did it). Introductions use I am / I'm / My name is.",
    naturalAlternative: "Hi, I'm Rahul — I work at TCS.",
    severity: "medium",
    lessonSlug: "introduce-yourself-naturally",
    practicePrompts: [
      "Introduce yourself in 3 sentences as if meeting a new colleague.",
      "Introduce yourself for a job interview.",
    ],
    detection: { kind: "regex", patterns: ["^\\s*(myself|this is .* speaking|i am .* myself)\\b", "\\bmyself\\s+[a-z]{2,}\\s*(,|\\.|i\\s+am|here)\\b"] },
  },
  {
    key: "good-name",
    title: "What is your good name?",
    category: "naturalness",
    subcategory: "word-choice",
    description: "“Good name” isn’t used for asking someone’s name in English.",
    wrongExample: "May I know your good name?",
    correctExample: "What's your name? / Could I take your name?",
    why: "“Good name” in English means reputation (a person of good name). For names: What’s your name? (casual), May I have your name? (polite), What do you go by? (friendly).",
    naturalAlternative: "Sorry, I didn't catch your name.",
    severity: "low",
    lessonSlug: "introduce-yourself-naturally",
    practicePrompts: ["Ask a stranger for their name politely in three different ways."],
    detection: { kind: "regex", patterns: ["\\bgood\\s+name\\b"] },
  },
  {
    key: "passed-out",
    title: "I passed out in 2020",
    category: "naturalness",
    subcategory: "word-choice",
    description: "“Pass out” means faint (or graduate in Indian English).",
    wrongExample: "I passed out of Delhi University in 2020.",
    correctExample: "I graduated from Delhi University in 2020.",
    why: "Internationally, “pass out” means to lose consciousness (he passed out). For completing a course, say graduate, complete, finish, or be an alumnus of.",
    naturalAlternative: "I completed my degree at Delhi University in 2020.",
    severity: "medium",
    lessonSlug: "talk-about-your-education",
    practicePrompts: ["Describe your education in two sentences.", "Talk about a qualification you're proud of."],
    detection: { kind: "regex", patterns: ["\\b(passed|passing|pass)\\s+out\\s+(of|from|in|last|20)\\b"] },
  },
  {
    key: "very-much-good",
    title: "very much good / too much good",
    category: "vocab",
    subcategory: "word-choice",
    description: "“Very” strengthens adjectives, not adverbs of quantity.",
    wrongExample: "The food was very much good. Your work is too much good.",
    correctExample: "The food was very good. Your work is really good.",
    why: "very + adjective (very good), very much + verb (I like it very much). For emphasis on adjectives use really, extremely, incredibly.",
    severity: "low",
    lessonSlug: "intensifiers-without-overdoing",
    practicePrompts: ["Compliment someone's work using three intensifiers correctly."],
    detection: { kind: "regex", patterns: ["\\bvery\\s+much\\s+(good|bad|nice|great|beautiful|easy|hard|fast|slow|big|small|happy|sad|important)\\b", "\\btoo\\s+much\\s+(good|great|nice|beautiful|easy|important|amazing)\\b"] },
  },
  // ------------------------------------------------------------------- style
  {
    key: "filler-actually",
    title: "Overusing “actually”",
    category: "style",
    subcategory: "fillers",
    description: "“Actually” in almost every sentence sounds like a crutch word.",
    wrongExample: "Actually I work in IT. Actually my manager is nice. Actually I agree.",
    correctExample: "I work in IT. My manager is nice. I agree.",
    why: "Filler words are fine occasionally — but using the same one repeatedly makes speech sound nervous and repetitive. Listeners start hearing the filler instead of your idea.",
    naturalAlternative: "In fact... / To be honest... / Honestly... (vary your openings)",
    severity: "low",
    lessonSlug: "sound-native-without-fillers",
    practicePrompts: [
      "Speak for 60 seconds about your job without using “actually”.",
      "Explain a process while avoiding crutch words.",
    ],
    detection: { kind: "filler", patterns: ["actually"] },
  },
  {
    key: "filler-basically",
    title: "Overusing “basically”",
    category: "style",
    subcategory: "fillers",
    description: "“Basically” before every explanation weakens it.",
    wrongExample: "Basically I wake up early. Basically I work from home.",
    correctExample: "I wake up early. I work from home.",
    why: "One “basically” can set up a summary. Repeated, it signals hesitation. Cut it — your sentence is already simple enough.",
    severity: "low",
    lessonSlug: "sound-native-without-fillers",
    practicePrompts: ["Explain your morning routine with no filler words."],
    detection: { kind: "filler", patterns: ["basically"] },
  },
  {
    key: "filler-like",
    title: "Overusing “like”",
    category: "style",
    subcategory: "fillers",
    description: "“Like” used as a pause (not meaning “similar to”) is a classic hesitation marker.",
    wrongExample: "I was like, it was like, really like, expensive.",
    correctExample: "I thought it was really expensive.",
    why: "As a comparison, “like” is normal (it tastes like home). As a pause between words it makes fluent thoughts sound uncertain. Notice it, then replace pauses with silence — silence sounds confident.",
    severity: "low",
    lessonSlug: "sound-native-without-fillers",
    practicePrompts: ["Tell a short story without saying “like”."],
    detection: { kind: "filler", patterns: ["like"] },
  },
  {
    key: "filler-you-know",
    title: "Overusing “you know”",
    category: "style",
    subcategory: "fillers",
    description: "“You know” sprinkled through sentences pulls attention from your point.",
    wrongExample: "The deadline was tight, you know, and we, you know, struggled.",
    correctExample: "The deadline was tight, and we struggled.",
    why: "Borrowed time from the listener. Occasionally it checks shared understanding; repeatedly it reads as lack of confidence.",
    severity: "low",
    lessonSlug: "sound-native-without-fillers",
    practicePrompts: ["Describe a challenge you faced using clean sentences."],
    detection: { kind: "filler", patterns: ["you know"] },
  },
  // ------------------------------------------------------------------ fluency
  {
    key: "filled-pauses",
    title: "Frequent um / uh",
    category: "fluency",
    subcategory: "hesitation",
    description: "Audible hesitation markers (um, uh, mm) slow you down and signal uncertainty.",
    wrongExample: "Um, I think, uh, we should, uh, postpone it.",
    correctExample: "I think we should postpone it.",
    why: "Silent pauses are stronger than filled ones. When searching for a word, pause quietly — native speakers do it constantly and it sounds thoughtful, not weak.",
    naturalAlternative: "Pause silently for a beat, then continue.",
    severity: "medium",
    lessonSlug: "pauses-that-sound-confident",
    practicePrompts: ["Speak for 60 seconds with silent pauses only."],
    detection: { kind: "fluency", patterns: ["um", "uh", "umm", "hmm"] },
  },
  {
    key: "long-pauses",
    title: "Long pauses while building sentences",
    category: "fluency",
    subcategory: "hesitation",
    description: "Pauses over ~1.5s mid-sentence break the listener’s flow.",
    wrongExample: "I went to the... market... and bought... fruits.",
    correctExample: "I went to the market and bought fruits.",
    why: "Long mid-sentence pauses usually mean translating from your native language first. Fix: think in short phrase chunks (not whole sentences), and use fillers-free silent gaps at clause boundaries instead.",
    naturalAlternative: "Buy yourself time with: “Let me think for a second...” (once, not often).",
    severity: "medium",
    lessonSlug: "pauses-that-sound-confident",
    practicePrompts: ["Describe your day in 60 seconds, keeping pauses under one second."],
    detection: { kind: "fluency" },
  },
  {
    key: "word-repetition",
    title: "Repeating the same word in one answer",
    category: "fluency",
    subcategory: "redundancy",
    description: "Repeating one word repeatedly (very very really really) signals limited range.",
    wrongExample: "The work is very busy, very long and very stressful.",
    correctExample: "The work is intense, long and stressful.",
    why: "Repetition is a vocabulary gap in disguise. Fix: after speaking, note the repeated word and collect two synonyms — then use them next time.",
    severity: "low",
    lessonSlug: "expand-your-sentence-range",
    practicePrompts: ["Describe your job using five different adjectives."],
    detection: { kind: "fluency" },
  },
  // ------------------------------------------------------------- pronunciation
  {
    key: "th-sound",
    title: "th sounds spoken as t/d",
    category: "pronunciation",
    subcategory: "consonants",
    description: "“think”, “this”, “three” lose their /θ/ /ð/ sounds.",
    wrongExample: "I tink it is dis way to ree tree.",
    correctExample: "I think it is this way to reach three.",
    why: "Put the tongue tip lightly BETWEEN the teeth (not behind them) and let air flow: think /θɪŋk/, this /ðɪs/. Practice minimal pairs: think–tink, tree–three, that–dat.",
    severity: "medium",
    lessonSlug: "th-sounds-in-everyday-words",
    practicePrompts: ["Say: I think thirty-three things about this thesis.", "Read: The three thieves thought about it."],
    detection: { kind: "pronunciation-transcript", patterns: ["\\b(tink|tis|dis|dat|te|tey|dere|tose|tink)\\b", "\\bd(e|a)\\s+(way|house|thing|time)\\b"] },
  },
  {
    key: "vw-sound",
    title: "w and v swapped",
    category: "pronunciation",
    subcategory: "consonants",
    description: "“want” vs “vant”, “very” vs “wery”.",
    wrongExample: "I wery much want to werk on dis.",
    correctExample: "I very much want to work on this.",
    why: "/v/ is lip-and-teeth (touch top teeth to lower lip). /w/ is rounded lips with no teeth contact. Minimal pairs: vine–wine, very–wery, vet–wet.",
    severity: "medium",
    lessonSlug: "w-vs-v-sounds",
    practicePrompts: ["Say: Victor wasted a very warm winter.", "Say: We visited the village with wine."],
    detection: { kind: "pronunciation-transcript", patterns: ["\\bwery\\b", "\\bwant(ed|ing)?\\s+to\\b.*\\bv", "\\b(ver|wer|wery|wine|vine)\\w*\\b"] },
  },
  // ------------------------------------------------------- further professional
  {
    key: "could-you-kindly",
    title: "kindly + please double politeness",
    category: "style",
    subcategory: "professional",
    description: "“Kindly” and “please” together sound over-formal or translated.",
    wrongExample: "Kindly please update the sheet at the earliest.",
    correctExample: "Could you update the sheet today?",
    why: "Modern professional English prefers contractions and questions over imperatives with “kindly”: Can you..., Could you..., Would you mind...",
    naturalAlternative: "Would you mind updating the sheet today?",
    severity: "low",
    lessonSlug: "emails-that-get-replies",
    practicePrompts: ["Ask a colleague for an update without using kindly."],
    detection: { kind: "regex", patterns: ["\\bkindly\\s+please\\b", "\\bkindly\\s+(do|share|update|confirm|revert|send|reply)\\b", "\\bat\\s+the\\s+earliest\\b"] },
  },
  {
    key: "i-agree-too-much",
    title: "No, no — agreeing styles",
    category: "naturalness",
    subcategory: "turn-taking",
    description: "Starting every reply with “yes” or “no” sounds scripted.",
    wrongExample: "Yes, I agree. Yes, my name is Rahul. Yes, I work in IT.",
    correctExample: "Absolutely — I'm Rahul, by the way. I work in IT.",
    why: "Vary agreement: Absolutely / That's right / I'd say so / You're right / Not quite — actually... Variety keeps conversation alive and sounds confident.",
    severity: "low",
    lessonSlug: "agreeing-and-disagreeing-smoothly",
    practicePrompts: ["Agree with three different statements using different phrases."],
    detection: { kind: "regex", patterns: ["^(yes|no)(,|\\.)\\s*(yes|no)\\b"] },
  },
  {
    key: "ending-sentences-up",
    title: "Up-talk (statement ending like a question)",
    category: "pronunciation",
    subcategory: "intonation",
    description: "Rising pitch at the end of every statement makes statements sound like questions.",
    wrongExample: "I finished the report? And then I sent it?",
    correctExample: "I finished the report and then I sent it.",
    why: "Declarative sentences fall in pitch at the end. If every line rises, listeners wait for a question that never comes — it weakens assertions in meetings.",
    naturalAlternative: "End statements with a downward pitch.",
    severity: "low",
    lessonSlug: "sounding-confident-intonation",
    practicePrompts: ["State three facts about yourself with falling intonation."],
    detection: { kind: "fluency" },
  },
];
