import type { PodcastSeed } from "./types";

const seg = (orderIndex: number, startMs: number, text: string) => ({
  orderIndex,
  startMs,
  endMs: startMs + Math.round(text.split(/\s+/).length * 380),
  text,
});

export const podcasts: PodcastSeed[] = [
  {
    slug: "how-ai-changed-my-morning-routine",
    title: "How AI Changed My Morning Routine",
    topic: "technology",
    description: "A lighthearted look at alarm apps, smart summaries and what actually still needs a human.",
    level: "beginner",
    durationSec: 210,
    coverEmoji: "🤖",
    publishedDate: "2026-09-12",
    featured: true,
    vocabularyWords: ["subscription", "update", "feature"],
    transcript: [
      seg(1, 0, "Every weekday I wake up at six thirty, and lately my phone has been doing most of the thinking for me."),
      seg(2, 8000, "It picks a gentle alarm, then hands me a summary of overnight messages before my coffee is ready."),
      seg(3, 17000, "The feature I actually love is the commute alert — it tells me to leave ten minutes early when the road is bad."),
      seg(4, 26000, "What still needs a human is deciding what actually matters. A list is not a priority."),
      seg(5, 35000, "So my rule is simple: automation prepares the information, and I make the call."),
      seg(6, 43000, "One warning — turn off the notifications you don't read. They're just noise wearing a helpful costume."),
      seg(7, 52000, "If you change one thing tomorrow, let it be the overnight summary. Two minutes, and you start the day informed."),
      seg(8, 61000, "That's it for this episode — try the two-minute test and tell me what you cut."),
    ],
    questions: [
      { type: "main_idea", prompt: "What is the episode mainly about?", options: ["Why humans should stop using phones", "Using AI to prepare information while humans make decisions", "How to wake up earlier", "The history of alarms"], correctIndex: 1, explanation: "The speaker's rule — automation prepares, I decide — is the central idea.", orderIndex: 1 },
      { type: "detail", prompt: "Which feature does the speaker love most?", options: ["The gentle alarm", "The overnight message summary", "The commute alert", "The coffee timer"], correctIndex: 2, explanation: "He says the commute alert — leave ten minutes early — is the one he loves.", orderIndex: 2 },
      { type: "inference", prompt: "What does 'notifications wearing a helpful costume' suggest?", options: ["Notifications are secretly useful", "They look helpful but are really distractions", "Costumes are fun", "You should buy new apps"], correctIndex: 1, explanation: "The metaphor means they pretend to help while adding noise.", orderIndex: 3 },
      { type: "vocabulary", prompt: "In the episode, a 'feature' is...", options: ["a flaw in software", "a part of a product that does a job", "a surprise party", "a type of subscription"], correctIndex: 1, explanation: "feature = a capability of a product (see vocabulary list).", orderIndex: 4 },
    ],
  },
  {
    slug: "the-4-day-week-debate",
    title: "The Four-Day Week Debate",
    topic: "career",
    description: "Two views on compressed schedules: output vs. overlap, and what teams should measure.",
    level: "intermediate",
    durationSec: 260,
    coverEmoji: "🗓️",
    publishedDate: "2026-09-19",
    vocabularyWords: ["workload", "benchmark", "deadline"],
    transcript: [
      seg(1, 0, "Let's talk about the four-day week, because every second conversation at conferences ends up there."),
      seg(2, 9000, "Supporters argue that hours are a lazy metric. What you should measure is output per person."),
      seg(3, 19000, "Critics reply that some roles can't shrink — support desks and hospitals don't get to close on Friday."),
      seg(4, 28000, "The interesting trials show a pattern: when teams must cut a day, they finally kill the meetings nobody needed."),
      seg(5, 38000, "That's the real effect. The calendar gets trimmed, and focus time doubles."),
      seg(6, 47000, "But it only works if managers agree on what done looks like. Vague goals plus fewer days equals chaos."),
      seg(7, 57000, "So before you copy anyone, write down your workload in tasks, not hours. Then decide what you'd drop."),
      seg(8, 67000, "Four days is not magic. Honest measurement is."),
    ],
    questions: [
      { type: "main_idea", prompt: "What is the speaker's overall point?", options: ["Four-day weeks always fail", "Measurement and clear goals matter more than the number of days", "Hospitals should close on Fridays", "Meetings are useless but fun"], correctIndex: 1, explanation: "The closing line: four days isn't magic — honest measurement is.", orderIndex: 1 },
      { type: "detail", prompt: "What do critics say about some roles?", options: ["They are too easy", "They cannot simply reduce hours", "They love meetings", "They already work four days"], correctIndex: 1, explanation: "Support desks and hospitals can't just close early.", orderIndex: 2 },
      { type: "inference", prompt: "Why do meetings shrink in trials?", options: ["Managers get angry", "Teams must cut time, so low-value meetings go first", "Calendars break", "Employees sleep more"], correctIndex: 1, explanation: "Cutting a day forces teams to remove unnecessary meetings.", orderIndex: 3 },
      { type: "speaker", prompt: "How does the speaker most likely feel?", options: ["Fiercely opposed to change", "Open but demanding evidence", "Certain that all companies should switch", "Indifferent"], correctIndex: 1, explanation: "He presents both sides and ends on measurement — evidence-first.", orderIndex: 4 },
    ],
  },
  {
    slug: "why-we-remember-stories-not-slides",
    title: "Why We Remember Stories, Not Slides",
    topic: "productivity",
    description: "The neuroscience of narrative, plus three ways to structure any presentation.",
    level: "intermediate",
    durationSec: 240,
    coverEmoji: "📖",
    publishedDate: "2026-08-29",
    vocabularyWords: ["abstract", "articulate", "concise"],
    transcript: [
      seg(1, 0, "You can show someone a hundred slides, and a week later they'll remember one story."),
      seg(2, 8000, "That's not a failure of your design. It's how memory works — narrative gives information a place to live."),
      seg(3, 18000, "A plot creates tension: something is at stake, someone acts, something changes."),
      seg(4, 26000, "Data answers what. Stories answer why anyone should care about the what."),
      seg(5, 35000, "So structure every presentation in three beats. First, the situation as it was."),
      seg(6, 43000, "Second, the moment something broke or opportunity appeared — that's your tension."),
      seg(7, 52000, "Third, the change and the proof: numbers, quotes, before and after."),
      seg(8, 61000, "Keep the slides abstract — one idea per screen — and let your voice carry the story."),
      seg(9, 70000, "Try it next week. Open with a story, not an agenda."),
    ],
    questions: [
      { type: "main_idea", prompt: "What is the episode arguing?", options: ["Slides should be removed entirely", "Stories make information memorable, so structure talks narratively", "Data never matters", "Memory is unreliable"], correctIndex: 1, explanation: "Narrative gives information a place to live — structure talks in three beats.", orderIndex: 1 },
      { type: "detail", prompt: "What is the second beat of the three-beat structure?", options: ["The situation as it was", "The moment of tension or opportunity", "The agenda", "The thank-you slide"], correctIndex: 1, explanation: "Situation → tension → change with proof.", orderIndex: 2 },
      { type: "inference", prompt: "'Keep slides abstract' means...", options: ["Use fewer words and let the speaker elaborate", "Draw abstract art", "Avoid all detail in speech", "Never use charts"], correctIndex: 0, explanation: "One idea per screen; the speaker carries the detail.", orderIndex: 3 },
      { type: "vocabulary", prompt: "'Abstract' in this episode most nearly means...", options: ["not concrete or detailed on the screen", "summary at the start of a paper", "mathematical", "abstract paintings"], correctIndex: 0, explanation: "Here it means general/non-detailed visuals; the other meaning (paper summary) also appears in the word list.", orderIndex: 4 },
    ],
  },
  {
    slug: "reading-the-room-in-any-language",
    title: "Reading the Room in Any Language",
    topic: "culture",
    description: "How tone, pace and silence communicate — even when your vocabulary is small.",
    level: "intermediate",
    durationSec: 230,
    coverEmoji: "👀",
    publishedDate: "2026-09-05",
    vocabularyWords: ["small talk", "acquaintance", "catch up"],
    transcript: [
      seg(1, 0, "When you're speaking a second language, you think everyone is judging your words."),
      seg(2, 8000, "In reality, they're reading your pace, your volume and where you put the stress."),
      seg(3, 17000, "Rising pitch at the end of every sentence makes statements sound like questions."),
      seg(4, 25000, "Fast, flat speech sounds nervous. Slow, falling speech sounds decided."),
      seg(5, 34000, "Silence is a tool too. A two-second pause before answering reads as thoughtful, not slow."),
      seg(6, 43000, "Watch how the room reacts to your openings, not your grammar. Eye contact tells you if you've been understood."),
      seg(7, 53000, "And when in doubt, mirror the other person's speed. Matching pace builds trust faster than perfect pronunciation."),
      seg(8, 63000, "Language gets you in the room. Delivery decides whether they lean in."),
    ],
    questions: [
      { type: "main_idea", prompt: "What does the speaker emphasize?", options: ["Grammar is the top priority", "Delivery — pace, pitch, pause — matters as much as words", "Silence should be avoided", "Volume should always be loud"], correctIndex: 1, explanation: "Listeners read pace, volume and stress more than grammar.", orderIndex: 1 },
      { type: "detail", prompt: "What does rising pitch at the end of statements do?", options: ["Sounds confident", "Makes statements sound like questions", "Improves grammar", "Speeds you up"], correctIndex: 1, explanation: "Up-talk leaves listeners waiting for a question.", orderIndex: 2 },
      { type: "inference", prompt: "A two-second pause before answering suggests...", options: ["You forgot the language", "You are thoughtful and controlled", "Your mic is broken", "You disagree strongly"], correctIndex: 1, explanation: "Silence reads as thoughtfulness when used deliberately.", orderIndex: 3 },
      { type: "speaker", prompt: "The speaker's attitude toward second-language speakers is...", options: ["dismissive", "encouraging and practical", "strictly formal", "confused"], correctIndex: 1, explanation: "He gives usable tactics and ends with an empowering line.", orderIndex: 4 },
    ],
  },
  {
    slug: "money-talk-for-first-jobs",
    title: "Money Talk for First Jobs",
    topic: "business",
    description: "Salary, negotiation and the phrases that make you sound professional with numbers.",
    level: "beginner",
    durationSec: 250,
    coverEmoji: "💰",
    publishedDate: "2026-08-22",
    vocabularyWords: ["negotiate", "invoice", "profit"],
    transcript: [
      seg(1, 0, "Your first job will teach you skills, and hopefully, how to talk about money without blushing."),
      seg(2, 9000, "Three words will follow you everywhere: salary, bonus and benefits."),
      seg(3, 17000, "Salary is what you're paid. Bonus depends on results. Benefits are health cover, leave and retirement contributions."),
      seg(4, 27000, "When they ask your expectation, give a range you can defend with market data."),
      seg(5, 36000, "Say it calmly: based on similar roles in this city, I'm targeting this band."),
      seg(6, 45000, "And remember — negotiate politely once. The sentence 'is there flexibility on that number?' costs you nothing."),
      seg(7, 55000, "Later, as a freelancer, you'll send invoices and track profit, which is what remains after costs."),
      seg(8, 65000, "Money is just another vocabulary. The more you say it out loud, the less scary it gets."),
    ],
    questions: [
      { type: "main_idea", prompt: "What is the episode's purpose?", options: ["To teach investing", "To make first-time workers comfortable discussing money professionally", "To explain accounting formulas", "To sell a course"], correctIndex: 1, explanation: "Money is another vocabulary — say it out loud until it's not scary.", orderIndex: 1 },
      { type: "detail", prompt: "What are benefits?", options: ["Your monthly salary", "Health cover, leave and retirement contributions", "The profit after costs", "Shares only"], correctIndex: 1, explanation: "The speaker lists health cover, leave and retirement as benefits.", orderIndex: 2 },
      { type: "vocabulary", prompt: "'Profit' means...", options: ["money you're paid monthly", "money left after costs", "a bill you send", "your salary expectation"], correctIndex: 1, explanation: "Profit = what remains after costs.", orderIndex: 3 },
      { type: "inference", prompt: "The phrase 'costs you nothing' suggests that...", options: ["negotiation is free and safe to attempt", "fees apply to asking", "you should never ask", "ranges are forbidden"], correctIndex: 0, explanation: "Asking politely for flexibility has no downside.", orderIndex: 4 },
    ],
  },
  {
    slug: "the-art-of-small-talk",
    title: "The Art of Small Talk",
    topic: "everyday",
    description: "Openers, follow-ups and graceful exits — the two minutes before every real conversation.",
    level: "beginner",
    durationSec: 200,
    coverEmoji: "☕️",
    publishedDate: "2026-09-15",
    vocabularyWords: ["icebreaker", "catch up", "acquaintance"],
    transcript: [
      seg(1, 0, "Small talk isn't fake. It's the handshake that happens before real conversation."),
      seg(2, 7000, "Structure it in three moves: open, share, hand back."),
      seg(3, 14000, "Open with something you both can see — the queue, the weather, the meeting that just ended."),
      seg(4, 23000, "Share one line about yourself, then hand the ball back: how's your week going so far?"),
      seg(5, 32000, "Keep topics light. Politics, salary and health are for people who already know you."),
      seg(6, 40000, "If you're stuck, ask a follow-up instead of a new question. People love talking about how they made a decision."),
      seg(7, 50000, "And exit cleanly: anyway, shall we get started? That one sentence moves everyone to work."),
    ],
    questions: [
      { type: "main_idea", prompt: "How does the speaker define small talk?", options: ["A necessary performance", "A handshake before real conversation", "A waste of time", "A test of grammar"], correctIndex: 1, explanation: "He explicitly calls it the handshake that precedes real conversation.", orderIndex: 1 },
      { type: "detail", prompt: "What are the three moves?", options: ["Open, share, hand back", "Ask, answer, leave", "Greet, debate, exit", "Listen, agree, run"], correctIndex: 0, explanation: "Open with shared context, share one line, hand back with a question.", orderIndex: 2 },
      { type: "inference", prompt: "Why ask follow-ups instead of new questions?", options: ["It saves time", "People enjoy explaining their decisions", "It ends the chat", "It shows off vocabulary"], correctIndex: 1, explanation: "The speaker says people love talking about how they made a decision.", orderIndex: 3 },
      { type: "detail", prompt: "Which exit line does he recommend?", options: ["Anyway, shall we get started?", "Goodbye forever", "I'm bored now", "Meeting cancelled"], correctIndex: 0, explanation: "The final sentence he recommends for moving to work.", orderIndex: 4 },
    ],
  },
  {
    slug: "what-makes-a-team-trust-you",
    title: "What Makes a Team Trust You",
    topic: "business",
    description: "Reliability, clarity and credit — the quiet habits that build reputation at work.",
    level: "advanced",
    durationSec: 270,
    coverEmoji: "🤝",
    publishedDate: "2026-09-22",
    vocabularyWords: ["stakeholder", "escalate", "handover"],
    transcript: [
      seg(1, 0, "Talent gets you hired. Trust gets you promoted — and trust is built in small, boring moments."),
      seg(2, 9000, "First: say what will happen, then make it happen. Under-promise is overused advice; the real habit is just never letting a commitment quietly expire."),
      seg(3, 21000, "If you can't make it, escalate early. Bad news travels well when it travels fast."),
      seg(4, 30000, "Second: clarity beats brilliance. Stakeholders forgive rough edges; they don't forgive ambiguity about who owns what."),
      seg(5, 41000, "Third: share credit in public and take blame in private. Teams remember who did that."),
      seg(6, 50000, "Fourth: write a real handover when you leave. Nothing signals professionalism like clean notes."),
      seg(7, 60000, "None of this requires charisma. It requires a calendar reminder and a short memory for your own wins."),
      seg(8, 70000, "Do those for a year, and the room starts asking for your opinion before you speak."),
    ],
    questions: [
      { type: "main_idea", prompt: "What builds trust at work, according to the speaker?", options: ["Charisma and long hours", "Reliability, clarity, credit-sharing and clean handovers", "Constant self-promotion", "Avoiding bad news"], correctIndex: 1, explanation: "Four habits: commitments, clarity, credit/blame, handovers.", orderIndex: 1 },
      { type: "detail", prompt: "What does the speaker advise when you can't meet a commitment?", options: ["Hide it", "Escalate early", "Resign", "Blame the tool"], correctIndex: 1, explanation: "'Bad news travels well when it travels fast.'", orderIndex: 2 },
      { type: "inference", prompt: "'A short memory for your own wins' suggests...", options: ["Forget your achievements entirely", "Stay humble and focus on contribution, not credit", "You have a poor memory", "Write everything down"], correctIndex: 1, explanation: "It contrasts with demanding public credit — humility signals trust.", orderIndex: 3 },
      { type: "vocabulary", prompt: "In the episode, a 'stakeholder' is...", options: ["someone affected by the outcome", "a shareholder only", "a meeting minutes taker", "an intern"], correctIndex: 0, explanation: "Stakeholder = any person or group affected by a project's result.", orderIndex: 4 },
    ],
  },
  {
    slug: "sports-finals-and-lesson-plans",
    title: "Sports Finals and Lesson Plans",
    topic: "sports",
    description: "How athletes rehearse pressure — and what classrooms borrow from it.",
    level: "beginner",
    durationSec: 220,
    coverEmoji: "🏆",
    publishedDate: "2026-08-15",
    vocabularyWords: ["checkpoint", "initiative", "performance"],
    transcript: [
      seg(1, 0, "The final went to the last over, and honestly, the winning team had been practicing that exact scenario."),
      seg(2, 9000, "They don't train for winning. They train for the moment before winning — the noise, the fatigue, the decision."),
      seg(3, 19000, "Coaches call it pressure inoculation. You expose yourself to stress in practice so the real thing feels familiar."),
      seg(4, 29000, "Schools borrowed the idea. Students who speak in class twice a week get used to all eyes turning to them."),
      seg(5, 39000, "Confidence isn't a personality trait handed out at birth. It's evidence you survived something before."),
      seg(6, 48000, "So whatever scares you — presentations, interviews, ordering coffee in a rush — rehearse it small and often."),
      seg(7, 58000, "The big moment is just a small moment with better lighting."),
    ],
    questions: [
      { type: "main_idea", prompt: "What is the central lesson?", options: ["Winning is luck", "Rehearsing under pressure makes big moments feel familiar", "Sports are better than school", "Coaches are strict"], correctIndex: 1, explanation: "Pressure inoculation — practice the stress, not just the skill.", orderIndex: 1 },
      { type: "detail", prompt: "What do the winning team practice?", options: ["Only winning", "The moment before winning: noise, fatigue, decisions", "Cheering", "Nothing extra"], correctIndex: 1, explanation: "They train the scenario before the victory, not the victory itself.", orderIndex: 2 },
      { type: "inference", prompt: "'Confidence is evidence you survived something before' means...", options: ["Confidence comes from past experience", "Confidence is given by parents", "Confidence is fake", "Confidence needs talent"], correctIndex: 0, explanation: "Evidence of prior survival — experience creates confidence.", orderIndex: 3 },
      { type: "vocabulary", prompt: "'Performance' here refers to...", options: ["how well someone executes under pressure", "an invoice", "a school exam only", "a movie showing"], correctIndex: 0, explanation: "performance = how well you do your task (see vocabulary list).", orderIndex: 4 },
    ],
  },
  {
    slug: "one-week-in-a-new-city",
    title: "One Week in a New City",
    topic: "travel",
    description: "A narrated first week abroad: bookings, small mistakes and the phrases that saved the day.",
    level: "intermediate",
    durationSec: 260,
    coverEmoji: "✈️",
    publishedDate: "2026-09-08",
    vocabularyWords: ["itinerary", "layover", "accommodation"],
    transcript: [
      seg(1, 0, "I landed after a four-hour layover, tired enough to misread my entire itinerary."),
      seg(2, 8000, "Rule one: screenshot everything. Apps die at passport control, screenshots don't."),
      seg(3, 16000, "My accommodation was thirty minutes from the center — cheap, quiet, and a daily lesson in bus timetables."),
      seg(4, 26000, "The first mistake was ordering by pointing. The second was not confirming the price before the cab moved."),
      seg(5, 37000, "The phrase that saved me was simply: could you repeat that more slowly?"),
      seg(6, 45000, "People don't mind helping if you ask clearly and smile like you mean it."),
      seg(7, 54000, "By day five I had a favorite bakery, a working route home, and zero anxiety about asking strangers."),
      seg(8, 64000, "A city stops being foreign the moment your feet know the way to breakfast."),
    ],
    questions: [
      { type: "main_idea", prompt: "What does the episode describe?", options: ["A packing guide", "The first week in a new city and how confidence grew", "Flight reviews", "Hotel ratings"], correctIndex: 1, explanation: "A narrated first week — mistakes included — ending with familiarity.", orderIndex: 1 },
      { type: "detail", prompt: "Why screenshot everything?", options: ["Photos are pretty", "Apps may fail at passport control", "Paper is free", "To impress friends"], correctIndex: 1, explanation: "Apps die; screenshots don't.", orderIndex: 2 },
      { type: "inference", prompt: "'A city stops being foreign...' suggests that...", options: ["familiarity comes from daily routes and routines", "cities change daily", "you must buy a home", "tourists never adapt"], correctIndex: 0, explanation: "Knowing the way to breakfast = routine creates belonging.", orderIndex: 3 },
      { type: "vocabulary", prompt: "An 'itinerary' is...", options: ["a travel schedule", "a bus ticket", "a hotel receipt", "a currency exchange"], correctIndex: 0, explanation: "itinerary = planned route or schedule for a journey.", orderIndex: 4 },
    ],
  },
  {
    slug: "when-your-plan-falls-apart",
    title: "When Your Plan Falls Apart",
    topic: "science",
    description: "What psychology says about setbacks, and a three-step recovery script you can say out loud.",
    level: "advanced",
    durationSec: 280,
    coverEmoji: "🧩",
    publishedDate: "2026-09-26",
    vocabularyWords: ["resilient", "mitigate", "hypothesis"],
    transcript: [
      seg(1, 0, "Every plan is a hypothesis. You believe that if you do X, Y will follow — and sometimes the data disagrees."),
      seg(2, 10000, "Psychologists find that the difference between fragile and resilient people is not setback size, but the story they tell after."),
      seg(3, 22000, "The fragile story says: this means I can't. The resilient story says: this means my method can't — yet."),
      seg(4, 33000, "That tiny word swaps identity for strategy, and strategies can be changed."),
      seg(5, 42000, "Practically, recovery has three steps. Name the loss out loud, so it stops growing in the dark."),
      seg(6, 51000, "Then mitigate: shrink the next move until it's boring and doable this week."),
      seg(7, 61000, "Then rebuild the hypothesis with one variable changed, and run it small."),
      seg(8, 71000, "Plans don't fall apart because you dreamed too big. They fall apart because we rarely plan the recovery."),
    ],
    questions: [
      { type: "main_idea", prompt: "What is the episode's core argument?", options: ["Plans always fail", "Recovery is a skill: change the story, mitigate, rebuild the hypothesis", "Dreams are dangerous", "Data is useless"], correctIndex: 1, explanation: "Three-step recovery: name, mitigate, rebuild with one changed variable.", orderIndex: 1 },
      { type: "detail", prompt: "What is the resilient story?", options: ["I can't do this", "My method can't — yet", "Others caused this", "Nothing ever works"], correctIndex: 1, explanation: "Strategy can change; identity claims cannot.", orderIndex: 2 },
      { type: "inference", prompt: "'Shrink the next move until it's boring' means...", options: ["make it so small it feels easy", "cancel the project", "add more risk", "wait for motivation"], correctIndex: 0, explanation: "Small, doable actions restart momentum.", orderIndex: 3 },
      { type: "vocabulary", prompt: "To 'mitigate' means to...", options: ["make something bad less severe", "increase the damage", "postpone forever", "celebrate early"], correctIndex: 0, explanation: "mitigate = reduce severity (see vocabulary list).", orderIndex: 4 },
    ],
  },
  {
    slug: "the-5-minute-podcast-habit",
    title: "The Five-Minute Podcast Habit",
    topic: "news",
    description: "Why short daily listening compounds — and how to listen actively instead of passively.",
    level: "beginner",
    durationSec: 190,
    coverEmoji: "🎧",
    publishedDate: "2026-09-01",
    vocabularyWords: ["subscription", "update", "checkpoint"],
    transcript: [
      seg(1, 0, "You don't need an hour of English every day. You need five honest minutes."),
      seg(2, 7000, "Pick one short episode during your commute or before your coffee."),
      seg(3, 14000, "First pass: listen without pausing. Get the idea, tolerate the gaps."),
      seg(4, 22000, "Second pass: write down three phrases you'd actually say yourself."),
      seg(5, 30000, "That's it. The trick isn't the length — it's doing it before the day gets busy."),
      seg(6, 38000, "Two weeks of this beats one heroic Saturday of studying you'll never repeat."),
      seg(7, 47000, "Attention is the subscription you pay daily. Five minutes, every day, compounds."),
    ],
    questions: [
      { type: "main_idea", prompt: "What habit does the speaker recommend?", options: ["An hour of study daily", "Five minutes of listening daily, done early", "One long session on weekends", "Listening while multitasking always"], correctIndex: 1, explanation: "Five honest minutes, before the day gets busy.", orderIndex: 1 },
      { type: "detail", prompt: "What should you do on the second pass?", options: ["Pause every word", "Write three phrases you'd say yourself", "Skip listening", "Take a nap"], correctIndex: 1, explanation: "First pass = gist; second pass = three usable phrases.", orderIndex: 2 },
      { type: "inference", prompt: "'Before the day gets busy' implies...", options: ["schedule it early or it won't happen", "evenings are best", "busy days are better", "time doesn't matter"], correctIndex: 0, explanation: "The habit must be anchored early to survive a busy day.", orderIndex: 3 },
      { type: "main_idea", prompt: "Why is a daily subscription mentioned?", options: ["To advertise an app", "As a metaphor for paying attention every day", "Because podcasts cost money", "To discuss finance"], correctIndex: 1, explanation: "Attention is the subscription you pay daily — a metaphor.", orderIndex: 4 },
    ],
  },
];
