import type { ScenarioSeed } from "./types";

export const scenarios: ScenarioSeed[] = [
  // ------------------------------------------------------------------- free
  {
    slug: "free-talk-my-day",
    title: "Tell me about your day",
    category: "free",
    description: "An easy warm-up: describe your day so far in a few natural sentences.",
    difficulty: 1,
    tags: ["warmup", "daily"],
    skillFocus: "fluency",
    openingPrompt: "Hi! Tell me about your day so far — what have you been up to?",
  },
  {
    slug: "free-talk-weekend",
    title: "Your ideal weekend",
    category: "free",
    description: "Talk about last weekend and what you'd like to do next — past and future tenses mixed.",
    difficulty: 1,
    tags: ["warmup", "daily", "tenses"],
    skillFocus: "fluency",
    openingPrompt: "What did you do last weekend, and what's the plan for next one?",
  },
  {
    slug: "free-talk-hobby",
    title: "A hobby you love",
    category: "free",
    description: "Explain a hobby in depth: how you started, why you continue, what you'd tell a beginner.",
    difficulty: 1,
    tags: ["warmup", "personal"],
    skillFocus: "vocabulary",
    openingPrompt: "What's a hobby you really enjoy? How did you get into it?",
  },
  // ------------------------------------------------------------------ topic
  {
    slug: "topic-remote-work",
    title: "Remote vs. office work",
    category: "topic",
    description: "Argue both sides of remote work and land on your own opinion with reasons.",
    difficulty: 2,
    tags: ["opinion", "work"],
    skillFocus: "speaking",
    openingPrompt: "Remote or office — which works better and why? Give me both sides first.",
  },
  {
    slug: "topic-social-media",
    title: "Is social media doing more harm?",
    category: "topic",
    description: "Take a position on social media's impact and support it with two concrete examples.",
    difficulty: 2,
    tags: ["opinion", "technology"],
    skillFocus: "speaking",
    openingPrompt: "Some say social media does more harm than good. What's your take?",
  },
  {
    slug: "topic-ai-jobs",
    title: "AI and the future of jobs",
    category: "topic",
    description: "Discuss which jobs change, which survive, and what workers should learn next.",
    difficulty: 3,
    tags: ["opinion", "technology", "career"],
    skillFocus: "speaking",
    openingPrompt: "Will AI replace your job? Which tasks should humans keep?",
  },
  {
    slug: "topic-city-life",
    title: "City life vs. small towns",
    category: "topic",
    description: "Compare living options with clear contrasts: cost, pace, opportunity, community.",
    difficulty: 2,
    tags: ["opinion", "lifestyle"],
    skillFocus: "vocabulary",
    openingPrompt: "Big city or small town? Compare them like you're advising a friend.",
  },
  {
    slug: "topic-education-value",
    title: "Is a degree still worth it?",
    category: "topic",
    description: "Balance experience vs. credentials with examples from people you know.",
    difficulty: 3,
    tags: ["opinion", "career", "education"],
    skillFocus: "speaking",
    openingPrompt: "Degrees or bootcamps or self-teaching — what actually gets people hired?",
  },
  // -------------------------------------------------------------- situation
  {
    slug: "situation-late-meeting",
    title: "You'll be late to a meeting",
    category: "situation",
    description: "Call a colleague and explain you'll be 20 minutes late — apologetic, clear, with a plan.",
    difficulty: 2,
    tags: ["phone", "work", "apology"],
    skillFocus: "speaking",
    openingPrompt: "The meeting starts in 10 minutes but you're stuck in traffic. Call me and handle it.",
  },
  {
    slug: "situation-hotel-problem",
    title: "Hotel booking went wrong",
    category: "situation",
    description: "At the front desk: your reservation is missing and you check in tonight. Stay polite but firm.",
    difficulty: 2,
    tags: ["travel", "service", "complaint"],
    skillFocus: "speaking",
    openingPrompt: "Welcome to the hotel — how can I help? (Your booking isn't in the system. Go ahead.)",
  },
  {
    slug: "situation-return-item",
    title: "Returning a broken product",
    category: "situation",
    description: "Explain what broke, when you bought it, and exactly what outcome you want.",
    difficulty: 2,
    tags: ["service", "complaint", "daily"],
    skillFocus: "speaking",
    persona: { role: "Customer service agent", name: "Dana", style: "Calm and scripted", opening: "Thanks for holding — what seems to be the issue with your order?" },
    openingPrompt: "Thanks for calling support — tell me what happened with the product.",
  },
  {
    slug: "situation-cancel-appointment",
    title: "Cancel a doctor's appointment",
    category: "situation",
    description: "Call, cancel politely, and reschedule — dates, times and confirmation.",
    difficulty: 1,
    tags: ["phone", "daily", "politeness"],
    skillFocus: "speaking",
    openingPrompt: "Clinic reception speaking — how can I help you today?",
  },
  {
    slug: "situation-salary-pushback",
    title: "The offer is lower than expected",
    category: "situation",
    description: "Negotiate an offer: gratitude first, market data second, specific number third.",
    difficulty: 3,
    tags: ["interview", "negotiation", "career"],
    skillFocus: "confidence",
    persona: { role: "Recruiter", name: "Ms. Fernandes", style: "Friendly but fixed budget", opening: "So — we'd like to offer you eighteen LPA. Thoughts?" },
    openingPrompt: "The team loves you. Here's the offer — what do you think?",
  },
  {
    slug: "situation-explain-delay",
    title: "Explain a project delay",
    category: "situation",
    description: "Update a stakeholder: what slipped, why, the recovery plan, the new date.",
    difficulty: 3,
    tags: ["work", "update", "accountability"],
    skillFocus: "speaking",
    persona: { role: "Project sponsor", name: "Ravi", style: "Direct, wants numbers", opening: "You said Friday. It's Friday. Where are we?" },
    openingPrompt: "Status check — walk me through where the project stands.",
  },
  // ----------------------------------------------------------------- roleplay
  {
    slug: "roleplay-coffee-newcolleague",
    title: "Coffee with a new colleague",
    category: "roleplay",
    description: "Break the ice: teams, relocation, weekend plans — the classic first-coffee chat.",
    difficulty: 1,
    tags: ["smalltalk", "work", "icebreaker"],
    skillFocus: "confidence",
    persona: { role: "New colleague", name: "Meera", style: "Curious, asks follow-ups", opening: "Hey — I don't think we've met. I'm Meera, joined the design team last week." },
    openingPrompt: "Hi! Grabbing coffee too? So what team are you on?",
  },
  {
    slug: "roleplay-negotiate-freelance",
    title: "Negotiate a freelance rate",
    category: "roleplay",
    description: "A client wants your work cheaper. Hold your rate with scope, value and alternatives.",
    difficulty: 3,
    tags: ["money", "negotiation", "work"],
    skillFocus: "confidence",
    persona: { role: "Potential client", name: "Jonas", style: "Pushy, budget-conscious", opening: "Another studio quoted us half your rate. Can you match that?" },
    openingPrompt: "Thanks for the proposal — let's talk numbers.",
  },
  {
    slug: "roleplay-friend-recommend",
    title: "Recommend a series to a friend",
    category: "roleplay",
    description: "Persuade a friend to watch something: plot without spoilers, tone, why it suits them.",
    difficulty: 1,
    tags: ["smalltalk", "culture", "casual"],
    skillFocus: "fluency",
    persona: { role: "Friend", name: "Arjun", style: "Skeptical, easily bored", opening: "I've got nothing to watch. Convince me of something?" },
    openingPrompt: "Okay — why should I watch whatever you're about to suggest?",
  },
  {
    slug: "roleplay-parents-update",
    title: "Weekly call with parents",
    category: "roleplay",
    description: "The familiar update: work, health, food, future plans — warm and unhurried.",
    difficulty: 1,
    tags: ["personal", "family", "daily"],
    skillFocus: "fluency",
    persona: { role: "Parent", name: "Papa", style: "Warm, asks three times if you're eating well", opening: "So how is work going? Are you eating properly there?" },
    openingPrompt: "Hello beta! Tell me everything — how's work, how's health?",
  },
  {
    slug: "roleplay-return-to-gym",
    title: "Signing up at a gym",
    category: "roleplay",
    description: "Ask about plans, trainers, contracts — and negotiate before you commit.",
    difficulty: 2,
    tags: ["daily", "service", "money"],
    skillFocus: "speaking",
    persona: { role: "Gym salesperson", name: "Tariq", style: "Enthusiastic upseller", opening: "First time here? We've got an offer that ends today!" },
    openingPrompt: "Welcome! Are you looking at our annual or monthly plan?",
  },
  // --------------------------------------------------------------- interview
  {
    slug: "interview-tell-me-about-yourself",
    title: "Tell me about yourself",
    category: "interview",
    description: "Present → past → future in 60 seconds, tailored to the role you're interviewing for.",
    difficulty: 2,
    tags: ["interview", "opening"],
    skillFocus: "confidence",
    persona: { role: "Interviewer", name: "Hiring manager", style: "Neutral, timing you", opening: "Thanks for joining. So — tell me about yourself." },
    openingPrompt: "Let's start easy: tell me about yourself.",
  },
  {
    slug: "interview-strength-weakness",
    title: "Strengths and weaknesses",
    category: "interview",
    description: "One real strength with proof; one genuine weakness with the fix you've applied.",
    difficulty: 2,
    tags: ["interview", "classic"],
    skillFocus: "confidence",
    persona: { role: "Interviewer", name: "Hiring manager", style: "Probes for specifics", opening: "What would your teammates say is your biggest strength — and weakness?" },
    openingPrompt: "Tell me about a strength and a weakness. Be honest.",
  },
  {
    slug: "interview-conflict-story",
    title: "A conflict you handled",
    category: "interview",
    description: "STAR story about disagreement at work — facts, your actions, measurable resolution.",
    difficulty: 3,
    tags: ["interview", "star", "behavioral"],
    skillFocus: "confidence",
    persona: { role: "Interviewer", name: "Hiring manager", style: "Asks 'and then what?' repeatedly", opening: "Tell me about a time you had a conflict with a teammate." },
    openingPrompt: "Walk me through a conflict — and be specific about what YOU did.",
  },
  {
    slug: "interview-why-this-company",
    title: "Why this company?",
    category: "interview",
    description: "Show research: product, mission, one concrete reason it fits your next step.",
    difficulty: 2,
    tags: ["interview", "motivation"],
    skillFocus: "confidence",
    persona: { role: "Interviewer", name: "Hiring manager", style: "Tests whether you did homework", opening: "Why us? Plenty of companies — why this one?" },
    openingPrompt: "So why do you want to work here specifically?",
  },
];
